import { z } from "zod";

import {
    defineNotificationType,
    yesNoUnknownOptions,
    type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e unidade notificadora.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "EPIZOOTIA",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_epizooty_start",
        label: "Data do início da epizootia",
        kind: "date",
        schema: z.string().min(1, "Data obrigatória"),
        defaultValue: "",
      },
      {
        name: "ds_info_source",
        label: "Fonte da informação",
        kind: "text",
        schema: z.string().min(1, "Fonte obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_info_source_phone",
        label: "(DDD) Telefone da fonte",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "occurrence_location",
    title: "Dados de Ocorrência",
    description: "Localização geográfica onde os animais foram encontrados.",
    columns: 3,
    fields: [
      {
        name: "occurrence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "occurrence_city",
        label: "Município de Ocorrência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "occurrence_city_ibge_code",
        label: "Código (IBGE) do Município de Ocorrência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_district_code",
        label: "Código (Distrito)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_geocampo1",
        label: "Geocampo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_geocampo2",
        label: "Geocampo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_environment",
        label: "Ambiente",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
        options: [
          { label: "Domicílio", value: "1" },
          { label: "Parque, praça ou zoológico", value: "2" },
          { label: "Área silvestre", value: "3" },
          { label: "Reserva ecológica", value: "4" },
          { label: "Outro", value: "5" },
        ],
      },
    ],
  },
  {
    id: "lab_investigation",
    title: "Investigação Laboratorial",
    description: "Detalhes da coleta de material para exame.",
    columns: 2,
    fields: [
      {
        name: "st_material_collected",
        label: "Houve coleta de material?",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_collection",
        label: "Data da Coleta",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_material_liver",
        label: "Fígado",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_kidney",
        label: "Rim",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_spleen",
        label: "Baço",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_brain",
        label: "Cérebro",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_heart",
        label: "Coração",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_feces",
        label: "Fezes",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_serum",
        label: "Soro",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_total_blood",
        label: "Sangue total",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_material_other",
        label: "Outro material",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "ds_material_other_description",
        label: "Qual",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "animals_conclusion",
    title: "Animais e Conclusão",
    description: "Espécies acometidas e suspeitas diagnósticas.",
    columns: 2,
    fields: [
      {
        name: "tp_animal",
        label: "Tipo de Animal",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
        options: [
          { label: "Ave", value: "1" },
          { label: "Bovídeo", value: "2" },
          { label: "Canino", value: "3" },
          { label: "Equídeo", value: "4" },
          { label: "Felino", value: "5" },
          { label: "Morcego", value: "6" },
          { label: "Primata não humano", value: "7" },
          { label: "Canídeo selvagem", value: "8" },
          { label: "Outros", value: "9" },
        ],
      },
      {
        name: "ds_animal_other_description",
        label: "Especificar (Outros animais)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "nu_sick_animals",
        label: "Doentes (Qtd)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "0",
      },
      {
        name: "nu_dead_animals",
        label: "Mortos (Qtd)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "0",
      },
      {
        name: "tp_suspicion_1",
        label: "1ª Suspeita Diagnóstica",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
        options: [
          { label: "Raiva", value: "1" },
          { label: "Encefalite Equina", value: "2" },
          { label: "Febre do Vírus do Nilo Ocidental", value: "3" },
          { label: "Encefalite Espongiforme Bovina", value: "4" },
          { label: "Febre Amarela", value: "5" },
          { label: "Influenza Aviária", value: "6" },
          { label: "Outro", value: "7" },
        ],
      },
      {
        name: "ds_suspicion_other_description",
        label: "Especificar (Outra suspeita)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_suspicion_2",
        label: "2ª Suspeita Diagnóstica",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_suspicion_3",
        label: "3ª Suspeita Diagnóstica",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_lab_result",
        label: "Resultado laboratorial",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_lab_result_rabies",
        label: "Raiva",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lab_result_equine_encephalitis",
        label: "Encefalite equina",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lab_result_nile_fever",
        label: "Febre do Nilo",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lab_result_bovine_spongiform_encephalitis",
        label: "Encefalite espongiforme bovina",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lab_result_yellow_fever",
        label: "Febre amarela",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lab_result_avian_influenza",
        label: "Influenza aviária",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lab_result_other",
        label: "Outro",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "ds_lab_result_other_description",
        label: "Especificar (Outro resultado laboratorial)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  
] as const satisfies readonly NotificationSectionDefinition[]

export const epizootyNotificationDefinition = defineNotificationType({
  id: 4,
  slug: "epizooty",
  label: "Epizootia",
  description: `Definição do caso: Animal ou grupo de animais encontrados doentes e/ou mortos, incluindo ossadas, sem causa definida, que podem preceder a ocorrência de doenças em humanos.`,
  sections,
})
