import { z } from "zod";

import {
    defineNotificationType,
    educationLevelOptions,
    healthOutcomeOptions,
    ministryProtocolOptions,
    raceColorOptions,
    screeningTestOptions,
    sexOptions,
    yesNoUnknownOptions,
    type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
{
    id: "patient",
    title: "Dados do Paciente",
    description: "Capture o retrato do paciente na notificacao, mesmo quando ele ja existe no cadastro geral.",
    columns: 3,
    fields: [
        {
            name: "patient_name",
            label: "Nome",
            kind: "text",
            schema: z.string().min(3, "Nome obrigatorio"),
            defaultValue: "",
        },
        {
            name: "patient_cpf",
            label: "CPF",
            kind: "text",
            schema: z.string().min(11, "CPF obrigatorio"),
            defaultValue: "",
        },
        {
            name: "patient_birth_date",
            label: "Data de nascimento",
            kind: "date",
            schema: z.string().min(1, "Data de nascimento obrigatoria"),
            defaultValue: "",
        },
        {
            name: "sex",
            label: "Sexo",
            kind: "select",
            schema: z.string().min(1, "Sexo obrigatorio"),
            defaultValue: "",
            options: sexOptions,
        },
        {
            name: "race_color",
            label: "Raca/Cor",
            kind: "select",
            schema: z.string().min(1, "Raca/Cor obrigatoria"),
            defaultValue: "",
            options: raceColorOptions,
        },
        {
            name: "education_level",
            label: "Escolaridade",
            kind: "select",
            schema: z.string().min(1, "Escolaridade obrigatoria"),
            defaultValue: "",
            options: educationLevelOptions,
        },
        {
            name: "sus_card_number",
            label: "Cartao SUS",
            kind: "text",
            schema: z.string().min(1, "Cartao SUS obrigatorio"),
            defaultValue: "",
        },
        {
            name: "nu_sus_card",
            label: "Número do Cartão SUS",
            kind: "text",
            schema: optionalTextSchema,
            defaultValue: "",
        },
        {
            name: "residence_city",
            label: "Municipio",
            kind: "text",
            schema: z.string().min(1, "Municipio obrigatorio"),
            defaultValue: "",
        },
        {
            name: "residence_state",
            label: "Estado",
            kind: "text",
            schema: z.string().min(2, "Estado obrigatorio"),
            defaultValue: "",
        },
    ],
},
  {
    id: "complementary_data",
    title: "Dados Complementares do Caso",
    description: "Informações adicionais sobre a investigação epidemiológica.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "laboratory_data",
    title: "Dados do Laboratório",
    description: "Resultados de exames laboratoriais.",
    columns: 2,
    fields: [
      {
        name: "dt_coproscopy",
        label: "Data da Coproscopia",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_quantitative_analysis",
        label: "Análise Quantitativa",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "0 (zero)", value: "0" },
          { label: "1 (um) ou mais ovos", value: "1" },
        ],
      },
      {
        name: "st_qualitative_analysis",
        label: "Análise Qualitativa",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Não realizado", value: "3" },
        ],
      },
      {
        name: "st_other_exams",
        label: "OUTROS",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Não realizado", value: "3" },
        ],
      },
      {
        name: "ds_other_exams_specify",
        label: "Outros exames (especificar)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "treatment_data",
    title: "Tratamento",
    description: "Informações sobre o tratamento realizado.",
    columns: 2,
    fields: [
      {
        name: "st_treatment_done",
        label: "Fez Tratamento?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim - Praziquantel", value: "1" },
          { label: "Sim - Oxamniquine", value: "2" },
          { label: "Não", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_treatment",
        label: "Data do Tratamento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_treatment_reason_not_done",
        label: "Caso não tenha feito tratamento, qual o motivo?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Contra Indicação", value: "1" },
          { label: "Recusa", value: "2" },
          { label: "Ausente", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_result_verification_analysis",
        label: "Resultado de Análise de Verificação de Cura",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "0 (zero)", value: "0" },
          { label: "1 (um) ou mais ovos", value: "1" },
          { label: "Não realizado", value: "2" },
        ],
      },
      {
        name: "st_result_verification_samples",
        label: "Amostras Verificadas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "1ª amostra", value: "1" },
          { label: "2ª amostra", value: "2" },
          { label: "3ª amostra", value: "3" },
        ],
      },
      {
        name: "dt_result_3a_sample",
        label: "Data do Resultado da 3ª amostra",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "infection_location",
    title: "Local Provável de Infecção",
    description: "Informações sobre o local onde a infecção provavelmente ocorreu.",
    columns: 2,
    fields: [
      {
        name: "tp_clinical_form",
        label: "Especificar Forma Clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Intestinal", value: "1" },
          { label: "Hepato Intestinal", value: "2" },
          { label: "Hepato Esplênica", value: "3" },
          { label: "Aguda", value: "4" },
          { label: "Outra (especificar)", value: "5" },
        ],
      },
      {
        name: "ds_clinical_form_other_specify",
        label: "Especificar",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_autochthonous_residence_municipality",
        label: "O caso é autóctone do município de residência?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Indeterminado", value: "3" },
        ],
      },
      {
        name: "uf_infection",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "country_infection",
        label: "País",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection",
        label: "Município",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "district_infection",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "neighborhood_infection",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "property_name",
        label: "Nome da Propriedade (se área rural)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "water_collection_name",
        label: "Nome da Coleção Hídrica",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_work_related_disease",
        label: "Doença Relacionada ao Trabalho",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "conclusion",
    title: "Conclusão",
    description: "Evolução do caso e dados de encerramento.",
    columns: 2,
    fields: [
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Cura", value: "1" },
          { label: "Não Cura", value: "2" },
          { label: "Óbito por esquistossomose", value: "3" },
          { label: "Óbito por outras causas", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closure",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },

] as const satisfies readonly NotificationSectionDefinition[]

export const schistosomiasisNotificationDefinition = defineNotificationType({
  id: 5,
  slug: "schistosomiasis",
  label: "ESQUISTOSSOMOSE",
  description: `Caso CONFIRMADO: Todo indivíduo que apresente ovos viáveis de Schistosoma mansoni nas fezes ou em tecido submetido à biópsia.`,
  sections,
})
