import { z } from "zod";

import {
    defineNotificationType,
    educationLevelOptions,
    healthOutcomeOptions,
    ministryProtocolOptions,
    raceColorOptions,
    screeningTestOptions,
    sexOptions,
    yesNoUnknownOptions,
    type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "patient",
    title: "Dados do Paciente",
    description:  "Capture o retrato do paciente na notificacao, mesmo quando ele ja existe no cadastro geral.",
    columns: 3,
    fields: [
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(1, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_cpf",
        label: "CPF",
        kind: "text",
        schema: z.string().min(11, "CPF obrigatorio"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit_hour",
        label: "Hora",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_age_unit_day",
        label: "Dia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_age_unit_month",
        label: "Mês",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_age_unit_year",
        label: "Ano",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: [
          { label: "Masculino", value: "M" },
          { label: "Feminino", value: "F" },
          { label: "Ignorado", value: "I" },
        ],
      },
      {
        name: "st_pregnant",
        label: "Gestante",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: [
          { label: "Branca", value: "1" },
          { label: "Preta", value: "2" },
          { label: "Amarela", value: "3" },
          { label: "Parda", value: "4" },
          { label: "Indígena", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: [
          { label: "Analfabeto", value: "0" },
          { label: "1ª a 4ª série incompleta do EF", value: "1" },
          { label: "2ª série completa do EF", value: "2" },
          { label: "5ª a 8ª série incompleta do EF", value: "3" },
          { label: "Ensino fundamental completo", value: "4" },
          { label: "Ensino médio incompleto", value: "5" },
          { label: "Ensino médio completo", value: "6" },
          { label: "Educação superior incompleta", value: "7" },
          { label: "Educação superior completa", value: "8" },
          { label: "Ignorado", value: "9" },
          { label: "Não se aplica", value: "10" },
        ],
      },
      {
        name: "nu_sus_card",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_data",
    title: "Dados de Residência",
    description: "Localização de residência do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro (rua, avenida,...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street_code",
        label: "Código (Logradouro)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_resident_abroad",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "complementary_data",
    title: "Dados Complementares do Caso",
    description: "Informações adicionais sobre a investigação epidemiológica.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "epidemiological_antecedents",
    title: "Antecedentes Epidemiológicos",
    description: "Informações sobre ocorrência de epizootias e presença de vetores.",
    columns: 2,
    fields: [
      {
        name: "st_epizootics_occurrence",
        label: "Informar dados da investigação entomológica (mosquitos) e de epizootias",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_epizootics_occurrence_notes",
        label: "Ocorrência de Epizootias (Mortalidade de macacos)",
        kind: "textarea",
        schema: optionalTextSchema,
        defaultValue: "",
        fullWidth: true,
      },
      {
        name: "st_virus_isolation_mosquitoes",
        label: "Isolamento de vírus em mosquitos",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "ds_aedes_aegypti_presence",
        label: "Presença de mosquito Aedes aegypti em área urbana",
        kind: "textarea",
        schema: optionalTextSchema,
        defaultValue: "",
        fullWidth: true,
      },
    ],
  },
  {
    id: "clinical_data",
    title: "Dados Clínicos",
    description: "Sinais e sintomas, hospitalização e vacinação.",
    columns: 2,
    fields: [
      {
        name: "st_vaccinated_yellow_fever",
        label: "Vacinado Contra Febre Amarela",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_case_affirmative",
        label: "Caso Afirmativo, Data",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "uf_case_affirmative",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_case_affirmative",
        label: "Município",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_case_affirmative_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_case_affirmative",
        label: "Unidade de Saúde",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_case_affirmative_code",
        label: "Código",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_signs_symptoms",
        label: "Sinais e Sintomas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_abdominal_pain",
        label: "Dor abdominal",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_fever_signal",
        label: "Sinal de Faget (temperatura alta e frequência cardíaca lenta)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_hemorrhagic_syndromes",
        label: "Sinais hemorrágicos (hematêmese, melena, epistaxe, gengivorragia, etc.)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_renal_dysfunction",
        label: "Distúrbios de excreção renal (oligúria e/ou anúria)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
    ],
  },
  {
    id: "hospitalization_data",
    title: "Atendimento",
    description: "Dados de hospitalização.",
    columns: 2,
    fields: [
      {
        name: "st_hospitalized",
        label: "Ocorreu Hospitalização?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_hospitalization",
        label: "Data da Internação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "uf_hospitalization",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_hospitalization",
        label: "Município",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_hospitalization_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_hospitalization",
        label: "Unidade de Saúde",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_hospitalization_code",
        label: "Código",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "laboratory_exams",
    title: "Dados do Laboratório",
    description: "Resultados de exames laboratoriais.",
    columns: 2,
    fields: [
      {
        name: "ds_bilirubin_total",
        label: "Bilirrubina Total",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_bilirubin_direct",
        label: "Bilirrubina Direta",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_ast",
        label: "AST (TGO)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_alt",
        label: "ALT (TGP)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_collection_1a_sample",
        label: "Data da Coleta (1ª Amostra IgM)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_1a_sample",
        label: "Resultado da 1ª amostra (IgM)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "dt_collection_2a_sample",
        label: "Data da Coleta (2ª Amostra IgM)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_2a_sample",
        label: "Resultado da 2ª amostra (IgM)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_material_collected_viral_isolation",
        label: "Material Coletado (Isolamento Viral)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_collection_viral_isolation",
        label: "Data da Coleta (Isolamento Viral)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_viral_isolation",
        label: "Resultado do isolamento",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_result_histopathology",
        label: "Resultado (Histopatologia)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Compatível", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_result_immunohistochemistry",
        label: "Resultado (Imuno-histoquímica)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "dt_collection_rt_pcr",
        label: "Data da Coleta (RT-PCR)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_rt_pcr",
        label: "Resultado (RT-PCR)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
    ],
  },
  {
    id: "conclusion",
    title: "Conclusão",
    description: "Classificação final e local provável de infecção.",
    columns: 2,
    fields: [
      {
        name: "st_final_classification",
        label: "Classificação Final",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Silvestre", value: "1" },
          { label: "Febre Amarela Urbana", value: "2" },
          { label: "Descartado (especificar)", value: "3" },
        ],
      },
      {
        name: "st_confirmation_criterion",
        label: "Critério de Confirmação/Descarte",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico-Epidemiológico", value: "2" },
        ],
      },
      {
        name: "st_autochthonous_residence_municipality",
        label: "O caso é autóctone do município de residência?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Indeterminado", value: "3" },
        ],
      },
      {
        name: "uf_infection",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "country_infection",
        label: "País",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection",
        label: "Município",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "district_infection",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "neighborhood_infection",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_locality",
        label: "Localidade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_work_related_disease",
        label: "Doença Relacionada ao Trabalho",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_activity_developed_infection_site",
        label: "Atividade desenvolvida no local provável de infecção",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Trabalho", value: "1" },
          { label: "Turismo", value: "2" },
          { label: "Lazer", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Cura", value: "1" },
          { label: "Óbito por febre amarela", value: "2" },
          { label: "Óbito por outras causas", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closure",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },

] as const satisfies readonly NotificationSectionDefinition[]

export const yellowFeverNotificationDefinition = defineNotificationType({
  id: 6,
  slug: "yellow_fever",
  label: "FEBRE AMARELA",
  description: `CASO SUSPEITO: Indivíduo com quadro febril agudo, icterícia e/ou manifestações hemorrágicas, residente ou procedente de área de risco para febre amarela ou de locais com ocorrência de epizootias em primatas não humanos ou isolamento de vírus em vetores, nos últimos 15 dias, não vacinados contra febre amarela ou com estado vacinal ignorado.`,
  sections,
})
