import { z } from "zod";

import {
    defineNotificationType,
    educationLevelOptions,
    healthOutcomeOptions,
    ministryProtocolOptions,
    raceColorOptions,
    screeningTestOptions,
    sexOptions,
    yesNoUnknownOptions,
    type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "patient",
    title: "Dados do Paciente",
    description:
      "Capture o retrato do paciente na notificacao, mesmo quando ele ja existe no cadastro geral.",
    columns: 3,
    fields: [
      {
        name: "patient_name",
        label: "Nome",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatorio"),
        defaultValue: "",
      },
      {
        name: "patient_cpf",
        label: "CPF",
        kind: "text",
        schema: z.string().min(11, "CPF obrigatorio"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatoria"),
        defaultValue: "",
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatorio"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "race_color",
        label: "Raca/Cor",
        kind: "select",
        schema: z.string().min(1, "Raca/Cor obrigatoria"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatoria"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Cartao SUS",
        kind: "text",
        schema: z.string().min(1, "Cartao SUS obrigatorio"),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Municipio",
        kind: "text",
        schema: z.string().min(1, "Municipio obrigatorio"),
        defaultValue: "",
      },
      {
        name: "residence_state",
        label: "Estado",
        kind: "text",
        schema: z.string().min(2, "Estado obrigatorio"),
        defaultValue: "",
      },
    ],
  },
      {
        name: "st_pregnant",
        label: "Gestante",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "nu_sus_card",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_resident_abroad",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "clinical_lab_data",
    title: "Dados clínicos e laboratoriais",
    description: "Informações sobre a investigação clínica e doenças pré-existentes.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_fever",
        label: "Febre",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_headache",
        label: "Cefaleia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_vomiting",
        label: "Vômito",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_back_pain",
        label: "Dor nas costas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_arthritis",
        label: "Artrite",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_petechiae",
        label: "Petéquias",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_positive_tourniquet_test",
        label: "Prova do laço positiva",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_myalgia",
        label: "Mialgia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_exanthema",
        label: "Exantema",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_nausea",
        label: "Náuseas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_conjunctivitis",
        label: "Conjuntivite",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_arthralgia_intense",
        label: "Artralgia intensa",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_leukopenia",
        label: "Leucopenia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_retro_orbital_pain",
        label: "Dor retroorbital",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_diabetes",
        label: "Diabetes",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_hepatopathies",
        label: "Hepatopatias",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_arterial_hypertension",
        label: "Hipertensão arterial",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_autoimmune_diseases",
        label: "Doenças auto-imunes",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_hematological_diseases",
        label: "Doenças hematológicas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_chronic_renal_disease",
        label: "Doença renal crônica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_acid_peptic_disease",
        label: "Doença ácido-péptica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
    ],
  },
  {
    id: "laboratory_data",
    title: "Dados laboratoriais",
    description: "Resultados de exames laboratoriais para Dengue e Chikungunya.",
    columns: 2,
    fields: [
      {
        name: "dt_collection_1a_sample_chik",
        label: "Data da Coleta da 1ª Amostra (Chikungunya)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_collection_2a_sample_chik",
        label: "Data da Coleta da 2ª Amostra (Chikungunya)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_collection_prnt",
        label: "Data da Coleta (PRNT)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_chik_s1",
        label: "Resultado S1 (Chikungunya)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_result_chik_s2",
        label: "Resultado S2 (Chikungunya)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_result_prnt",
        label: "Resultado PRNT",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "dt_collection_igm_dengue",
        label: "Data da Coleta (IgM Dengue)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_igm_dengue",
        label: "Resultado (IgM Dengue)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "dt_collection_ns1",
        label: "Data da Coleta (NS1)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_ns1",
        label: "Resultado (NS1)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "dt_collection_isolation",
        label: "Data da Coleta (Isolamento)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_isolation",
        label: "Resultado (Isolamento)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "dt_collection_rt_pcr",
        label: "Data da Coleta (RT-PCR)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_result_rt_pcr",
        label: "Resultado (RT-PCR)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_serotype_dengue",
        label: "Sorotipo",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "DENV 1", value: "1" },
          { label: "DENV 2", value: "2" },
          { label: "DENV 3", value: "3" },
          { label: "DENV 4", value: "4" },
        ],
      },
      {
        name: "st_result_histopathology",
        label: "Histopatologia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Compatível", value: "1" },
          { label: "Incompatível", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_result_immunohistochemistry",
        label: "Imuno-histoquímica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
    ],
  },
  {
    id: "hospitalization_data",
    title: "Hospitalização",
    description: "Dados de hospitalização.",
    columns: 2,
    fields: [
      {
        name: "st_hospitalized",
        label: "Ocorreu Hospitalização?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_hospitalization",
        label: "Data da Internação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "uf_hospitalization",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_hospitalization",
        label: "Município do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_hospitalization_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_name",
        label: "Nome do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "conclusion",
    title: "Conclusão",
    description: "Classificação final e evolução do caso.",
    columns: 2,
    fields: [
      {
        name: "st_autochthonous_residence_municipality",
        label: "O caso é autóctone do município de residência?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Indeterminado", value: "3" },
        ],
      },
      {
        name: "uf_infection",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "country_infection",
        label: "País",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection",
        label: "Município",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "district_infection",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "neighborhood_infection",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_classification",
        label: "Classificação",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Dengue", value: "10" },
          { label: "Dengue com Sinais de Alarme", value: "11" },
          { label: "Dengue Grave", value: "12" },
          { label: "Chikungunya", value: "13" },
          { label: "Descartado", value: "1" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_confirmation_criterion",
        label: "Critério de Confirmação/Descarte",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico-Epidemiológico", value: "2" },
          { label: "Clínico", value: "3" },
          { label: "Em investigação", value: "4" },
        ],
      },
      {
        name: "st_clinical_presentation",
        label: "Apresentação clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Aguda", value: "1" },
          { label: "Crônica", value: "2" },
        ],
      },
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Cura", value: "1" },
          { label: "Óbito por agravo", value: "2" },
          { label: "Óbito por outras causas", value: "3" },
          { label: "Em investigação", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closure",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "dengue_alarm_severe_signs",
    title: "Sinais de Alarme e Dengue Grave",
    description: "Preencher os sinais clínicos para Dengue com Sinais de Alarme e Dengue Grave.",
    columns: 2,
    fields: [
      {
        name: "st_dengue_alarm_signs",
        label: "Dengue com sinais de alarme",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
        ],
      },
      {
        name: "st_vomiting_persistent",
        label: "Vômitos persistentes",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_abdominal_pain_intense_continuous",
        label: "Dor abdominal intensa e contínua",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_hepatomegaly_2cm",
        label: "Hepatomegalia > 2cm",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_platelet_decrease",
        label: "Queda abrupta de plaquetas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_lethargy_irritability",
        label: "Letargia ou irritabilidade",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_fluid_accumulation",
        label: "Acúmulo de líquidos",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_mucosal_bleeding",
        label: "Sangramento de mucosa/outras hemorragias",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_dengue_alarm_signs_start",
        label: "Data de início dos sinais de alarme",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_dengue_severe",
        label: "Dengue Grave",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
        ],
      },
      {
        name: "st_shock",
        label: "Choque",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_weak_rapid_pulse",
        label: "Pulso débil ou indetectável",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_tachycardia",
        label: "Taquicardia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_blood_pressure_pa_less_than_20",
        label: "PA convergente < 20 mmHg",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_cold_extremities",
        label: "Extremidades frias",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_capillary_refill_time",
        label: "Tempo de enchimento capilar",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_hypotension_arterial",
        label: "Hipotensão arterial",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_oliguria",
        label: "Oligúria",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_ast_alt_greater_than_1000",
        label: "AST/ALT > 1.000",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_myocarditis",
        label: "Miocardite",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_encephalopathy",
        label: "Encefalopatia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_other_organ_involvement",
        label: "Outros órgãos, especificar",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_dengue_severe_start",
        label: "Data de início dos sinais de gravidade",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },

] as const satisfies readonly NotificationSectionDefinition[]

export const dengueChikungunyaNotificationDefinition = defineNotificationType({
  id: 6,
  slug: "dengue_chikungunya",
  label: "DENGUE - CHIKUNGUNYA",
  description: `CASO SUSPEITO de dengue: Pessoa que viva ou tenha viajado nos últimos 14 dias para área onde esteja ocorrendo transmissão de dengue ou tenha presença de Ae.aegypti, que apresente febre, usualmente entre 2 e 7 dias, e apresente duas ou mais das seguintes manifestações: cefaleia, dor retroorbital, petéquias ou prova do laço positiva e leucopenia.\nCASO SUSPEITO de chikungunya: Febre de início súbito e artralgia ou artrite intensa com início agudo, não explicado por outras condições, que resida ou tenha viajado para áreas endêmicas, ou epidêmicas até 14 dias antes do início dos sintomas, ou que tenha vínculo epidemiológico com um caso importado confirmado.`,
  sections,
})
