import { z } from "zod"

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional()

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "HANTAVIROSE",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "A 98.8",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_symptoms_start",
        label: "Data dos Primeiros Sintomas",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "epidemiological_history",
    title: "Antecedentes Epidemiológicos",
    description: "Histórico de exposições e atividades de risco nos últimos 60 dias.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_military_training",
        label: "Treinamento militar em área rural ou silvestre",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_deforestation_farming",
        label: "Desmatamento, aragem de terra, plantio agrícola, colheita agrícola, corte de lenha",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_cleaning_storage",
        label: "Exposição e/ou limpeza de casa, despensa, galpão, depósitos, sótão, porão",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_grain_milling",
        label: "Moagem e/ ou armazenamento de grãos, fardos de lenha ou capim",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_sleeping_shelter",
        label: "Dormiu/descansou em barracas, galpão, paiol ou similares",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_cargo_transport",
        label: "Transporte e ou carregamento de cargas em geral",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_ecotourism",
        label: "Pescou, caçou, realizou turismo rural ou ecoturismo",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_rodent_contact",
        label: "Contato direto ou vestígios de rato silvestre",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "exposure_other",
        label: "Outras atividades ou exposições de risco",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "ds_exposure_other_spec",
        label: "Especifique outras atividades",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "clinical_data",
    title: "Dados Clínicos e Atendimento",
    description: "Histórico do primeiro atendimento e sinais clínicos.",
    columns: 3,
    fields: [
      {
        name: "dt_first_attendance",
        label: "Data do Primeiro Atendimento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_first_attendance_local",
        label: "Local do Primeiro Atendimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "symptom_fever", label: "Febre", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_dry_cough", label: "Tosse Seca", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_dyspnea", label: "Dispnéia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_acute_respiratory_failure", label: "Insuficiência Respiratória Aguda", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_headache", label: "Cefaléia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_generalized_myalgia", label: "Mialgia Generalizada", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_back_pain", label: "Dor Lombar (região dos rims)", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_abdominal_pain", label: "Dor Abdominal", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_hypotension", label: "Hipotensão", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_shock", label: "Choque", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_nausea_vomiting", label: "Náuseas / Vômito", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_diarrhea", label: "Diarréia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_chest_pain", label: "Dor Torácica", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_dizziness_vertigo", label: "Tontura / Vertigem", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_heart_failure", label: "Insuficiência Cardíaca", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_renal_failure", label: "Insuficiência Renal", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_neurological", label: "Sintomas Neurológicos", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_asthenia", label: "Astenia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_petechiae", label: "Petéquias (manchas de sangue sob a pele)", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_other_hemorrhagic", label: "Outras manifestações hemorrágicas", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "ds_other_hemorrhagic_spec", label: "Especificar manifestações hemorrágicas", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "symptom_other", label: "Outros sintomas", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "ds_symptom_other_spec", label: "Especificar outros sintomas", kind: "text", schema: optionalTextSchema, defaultValue: "" },
    ],
  },
  {
    id: "lab_investigation",
    title: "Dados do Laboratório",
    description: "Resultados laboratoriais, bioquímicos e exames de imagem.",
    columns: 3,
    fields: [
      {
        name: "st_blood_sample_collected",
        label: "Colheu Amostra de Sangue",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      { name: "lab_result_hematocrit", label: "Hematócrito maior que 45%", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "lab_result_thrombocytopenia", label: "Trombocitopenia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "lab_result_atypical_lymphocytes", label: "Linfócitos Atípicos", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "lab_result_urea_creatinine", label: "Aumento de Uréia e Creatinina", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "lab_result_tgo", label: "TGO", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "lab_result_tgp", label: "TGP", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      {
        name: "lab_result_leukocytes",
        label: "Leucócitos",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Normais", value: "1" },
          { label: "Aumentados com desvio à esquerda", value: "2" },
          { label: "Diminuídos (Leucopenia)", value: "3" },
          { label: "Aumentados sem desvio à esquerda", value: "4" },
          { label: "Não Realizado", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_chest_xray",
        label: "Realizou Radiografia do Tórax",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      { name: "xray_diffuse_infiltrate", label: "Infiltrado Pulmonar Difuso", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "xray_localized_infiltrate", label: "Infiltrado Pulmonar Localizado", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "xray_pleural_effusion", label: "Derrame Pleural", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      {
        name: "dt_serology_collection",
        label: "Data da Coleta Sorológica",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_serology_result",
        label: "Resultado Sorológico (IgM)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "st_immunohistochemistry_result",
        label: "Resultado da Imunohistoquímica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "dt_rtpcr_collection",
        label: "Data da Coleta RT-PCR",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_rtpcr_result",
        label: "Resultado RT-PCR",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
    ],
  },
  {
    id: "hospitalization_support",
    title: "Hospitalização e Suporte Terapêutico",
    description: "Dados referentes à internação do paciente e condutas aplicadas.",
    columns: 3,
    fields: [
      {
        name: "st_hospitalization",
        label: "Ocorreu Hospitalização",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_hospitalization",
        label: "Data da Internação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_uf",
        label: "UF do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city",
        label: "Município do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city_ibge_code",
        label: "Código (IBGE) do Município do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_name",
        label: "Nome do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_code",
        label: "Código do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_therapeutic_support",
        label: "Suporte Terapêutico",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      { name: "support_mechanical_ventilator", label: "Ficou no Respirador Mecânico", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "support_vasoactive_drugs", label: "Usou Drogas Vasoativas", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "support_antiviral", label: "Usou Medicamento Antiviral", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "support_corticoid", label: "Usou Corticóide", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "support_cpap_bipap", label: "CPAP/BIPAP", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "support_antibiotics", label: "Usou Antibióticos", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "support_other_treatment", label: "Outro Tipo de Tratamento", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
    ],
  },
  {
    id: "case_conclusion",
    title: "Conclusão",
    description: "Classificação final do agravo e encerramento epidemiológico.",
    columns: 3,
    fields: [
      {
        name: "tp_final_classification",
        label: "Classificação final",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Confirmado", value: "1" },
          { label: "Descartado", value: "2" },
        ],
      },
      {
        name: "tp_clinical_form",
        label: "Forma Clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Prodrômica ou inespecífica", value: "1" },
          { label: "Síndrome Cardiopulmonar por Hantavírus", value: "2" },
        ],
      },
      {
        name: "tp_diagnostic_criterion",
        label: "Critério de Diagnóstico",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico Epidemiológico", value: "2" },
        ],
      },
      {
        name: "lpi_is_autochthonous",
        label: "O caso é autóctone do município de residência?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Indeterminado", value: "3" },
        ],
      },
      {
        name: "lpi_uf",
        label: "UF LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_country",
        label: "País LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_city",
        label: "Município LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_city_ibge_code",
        label: "Código (IBGE) do Município LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_district",
        label: "Distrito LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_neighborhood",
        label: "Bairro LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_lpi_zone",
        label: "Zona do Provável Local de Infecção",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_lpi_environment",
        label: "Tipo de Ambiente",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Domiciliar", value: "1" },
          { label: "Trabalho", value: "2" },
          { label: "Lazer", value: "3" },
          { label: "Outro", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_lpi_location_relation",
        label: "Localização em Relação à Sede",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sul", value: "1" },
          { label: "Norte", value: "2" },
          { label: "Leste", value: "3" },
          { label: "Oeste", value: "4" },
        ],
      },
      {
        name: "nu_lpi_km",
        label: "Kilômetros até a Sede",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Cura", value: "1" },
          { label: "Óbito por hantavirose", value: "2" },
          { label: "Óbito por outra causa", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death_or_discharge",
        label: "Data do Óbito ou Alta",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_autopsy_performed",
        label: "Realizou Autópsia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_work_related",
        label: "Doença Relacionada ao Trabalho",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const hantavirusNotificationDefinition = defineNotificationType({
  id: 30,
  slug: "hantavirose",
  label: "Hantavirose",
  description: `Caso suspeito: Paciente com febre, mialgia, cefaléia e insuficiência respiratória aguda de etiologia não determinada, na primeira semana da doença ou exposição a situações de risco até 60 dias anteriores ao início dos sintomas.`,
  sections,
})
