import { z } from "zod"

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional()

const exposureTimelineOptions = [
  { label: "Sim, há menos de seis meses", value: "1" },
  { label: "Sim, há mais de seis meses", value: "2" },
  { label: "Não", value: "3" },
  { label: "Ignorado", value: "9" },
]

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "HEPATITES VIRAIS",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "B 19",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_symptoms_start",
        label: "Data dos Primeiros Sintomas",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "epidemiological_history",
    title: "Antecedentes Epidemiológicos",
    description: "Histórico de suspeitas, vacinação e exposições de risco.",
    columns: 3,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_suspicion",
        label: "Suspeita de",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Hepatite A", value: "1" },
          { label: "Hepatite B/C", value: "2" },
          { label: "Não especificada", value: "3" },
        ],
      },
      {
        name: "vaccine_hepatitis_a",
        label: "Tomou vacina para Hepatite A",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Completa", value: "1" },
          { label: "Incompleta", value: "2" },
          { label: "Não vacinado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "vaccine_hepatitis_b",
        label: "Tomou vacina para Hepatitis B",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Completa", value: "1" },
          { label: "Incompleta", value: "2" },
          { label: "Não vacinado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_institutionalized",
        label: "Institucionalizado em",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Creche", value: "1" },
          { label: "Escola", value: "2" },
          { label: "Asilo", value: "3" },
          { label: "Empresa", value: "4" },
          { label: "Penitenciária", value: "5" },
          { label: "Hospital/clínica", value: "6" },
          { label: "Outras", value: "7" },
          { label: "Não institucionalizado", value: "8" },
          { label: "Ignorado", value: "9" },
        ],
      },
      { name: "associated_hiv_aids", label: "Agravo associado: HIV/AIDS", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "associated_other_std", label: "Agravo associado: Outras DSTs", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "associated_viral_hepatitis", label: "Agravo associado: Hepatites Virais", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "contact_sexual", label: "Contato com portador: Sexual", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "contact_household", label: "Contato com portador: Domiciliar (não sexual)", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "contact_occupational", label: "Contato com portador: Ocupacional", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_injectable_meds", label: "Exposto a: Medicamentos Injetáveis", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_tattoo_piercing", label: "Exposto a: Tatuagem/Piercing", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_biological_material", label: "Exposto a: Acidente com Material Biológico", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_inhalant_drugs", label: "Exposto a: Drogas inaláveis ou Crack", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_injectable_drugs", label: "Exposto a: Drogas injetáveis", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_blood_transfusion", label: "Exposto a: Transfusão de sangue/derivados", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_acupuncture", label: "Exposto a: Acupuntura", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_surgical_treatment", label: "Exposto a: Tratamento Cirúrgico", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_contaminated_water_food", label: "Exposto a: Água/Alimento contaminado", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_multiple_partners", label: "Exposto a: Três ou mais parceiros sexuais", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_dental_treatment", label: "Exposto a: Tratamento Dentário", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_hemodialysis", label: "Exposto a: Hemodiálise", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_transplant", label: "Exposto a: Transplante", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      { name: "exp_other", label: "Exposto a: Outras exposições", kind: "select", schema: z.string(), defaultValue: "9", options: exposureTimelineOptions },
      {
        name: "dt_accident_transfusion",
        label: "Data do acidente ou transfusão ou transplante",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_uf",
        label: "UF da Exposição",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_city",
        label: "Município de Exposição",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_local",
        label: "Local de Exposição",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_phone",
        label: "Telefone do Local de Exposição",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "patient_referred_from",
        label: "Paciente encaminhado de",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Banco de sangue", value: "1" },
          { label: "Centro de Testagem e aconselhamento (CTA)", value: "2" },
          { label: "Não se aplica", value: "3" },
        ],
      },
    ],
  },
  {
    id: "lab_investigation",
    title: "Dados Laboratoriais",
    description: "Resultados de exames sorológicos e virológicos.",
    columns: 3,
    fields: [
      {
        name: "dt_collection_blood_bank",
        label: "Data da Coleta da Amostra Realizada em Banco de Sangue ou CTA",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "blood_bank_result_hbsag",
        label: "Resultado Banco de Sangue/CTA: HBsAg",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "blood_bank_result_anti_hbc",
        label: "Resultado Banco de Sangue/CTA: Anti-HBc (Total)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "blood_bank_result_anti_hcv",
        label: "Resultado Banco de Sangue/CTA: Anti-HCV",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_collection_serology",
        label: "Data da Coleta da Sorologia / Teste rápido",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "serology_anti_hav_igm",
        label: "Sorologia: Anti-HAV - IgM",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_hbsag",
        label: "Sorologia: HBsAg",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hbc_igm",
        label: "Sorologia: Anti-HBc IgM",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hbc_total",
        label: "Sorologia: Anti-HBc (Total)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hbs",
        label: "Sorologia: Anti-HBs",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_hbeag",
        label: "Sorologia: HBeAg",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hbe",
        label: "Sorologia: Anti-HBe",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hdv_total",
        label: "Sorologia: Anti-HDV Total",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hdv_igm",
        label: "Sorologia: Anti-HDV - IgM",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hev_igm",
        label: "Sorologia: Anti-HEV - IgM",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_anti_hcv",
        label: "Sorologia: Anti-HCV",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "serology_hcv_rna",
        label: "Sorologia: HCV-RNA",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente / Positivo", value: "1" },
          { label: "Não Reagente / Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não Realizado", value: "4" },
        ],
      },
      {
        name: "hcv_genotype",
        label: "Genótipo para HCV",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Genótipo 1", value: "1" },
          { label: "Genótipo 2", value: "2" },
          { label: "Genótipo 3", value: "3" },
          { label: "Genótipo 4", value: "4" },
          { label: "Genótipo 5", value: "5" },
          { label: "Genótipo 6", value: "6" },
          { label: "Não se aplica", value: "7" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "case_conclusion",
    title: "Conclusão",
    description: "Classificação final do agravo e encerramento epidemiológico.",
    columns: 3,
    fields: [
      {
        name: "tp_final_classification",
        label: "Classificação final",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Confirmação laboratorial", value: "1" },
          { label: "Confirmação clínico-epidemiológica", value: "2" },
          { label: "Descartado", value: "3" },
          { label: "Cicatriz Sorológica", value: "4" },
          { label: "Inconclusivo", value: "8" },
        ],
      },
      {
        name: "tp_clinical_form",
        label: "Forma Clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Hepatite Aguda", value: "1" },
          { label: "Hepatite Crônica / Portador assintomático", value: "2" },
          { label: "Hepatite Fulminante", value: "3" },
          { label: "Inconclusivo", value: "4" },
        ],
      },
      {
        name: "tp_etiological_classification",
        label: "Classificação Etiológica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Vírus A", value: "01" },
          { label: "Vírus B", value: "02" },
          { label: "Vírus C", value: "03" },
          { label: "Vírus B e D", value: "04" },
          { label: "Vírus E", value: "05" },
          { label: "Vírus B e C", value: "06" },
          { label: "Vírus A e B", value: "07" },
          { label: "Vírus A e C", value: "08" },
          { label: "Não se aplica", value: "09" },
        ],
      },
      {
        name: "tp_infection_source",
        label: "Provável Fonte / Mecanismo de Infecção",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sexual", value: "01" },
          { label: "Transfusional", value: "02" },
          { label: "Uso de drogas", value: "03" },
          { label: "Vertical", value: "04" },
          { label: "Acidente de trabalho", value: "05" },
          { label: "Hemodiálise", value: "06" },
          { label: "Domiciliar", value: "07" },
          { label: "Tratamento cirúrgico", value: "08" },
          { label: "Tratamento dentário", value: "09" },
          { label: "Pessoa / pessoa", value: "10" },
          { label: "Alimento / água contaminada", value: "11" },
          { label: "Outros", value: "12" },
          { label: "Ignorado", value: "99" },
        ],
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const viralHepatitisNotificationDefinition = defineNotificationType({
  id: 40,
  slug: "hepatites-virais",
  label: "Hepatites Virais",
  description: `CASO CONFIRMADO Hepatite A: - Indivíduo que apresente anti-HAV IgM reagente- Indivíduo que preencha as condições de caso suspeito e que apresente vínculo epidemiológico com caso confirmado (anti-HAV IgM reagente) dehepatite A- Menção de hepatite A em qualquer um dos campos da declaração de óbito ou após investigação do óbito por hepatite sem etiologia especificada.Hepatite B: - Indivíduo que apresente um ou mais dos marcadores reagentes ou exame de biologia molecular para hepatite B a seguir: . HBsAg reagente . Anti-HBc IgM reagente . HBV-DNA detectável- Menção de hepatite B em qualquer um dos campos da declaração de óbito ou após investigação do óbito por hepatite sem etiologia especificada.Hepatite C: - Indivíduo que apresente um ou mais dos marcadores reagentes ou exame de biologia molecular para hepatite C a seguir: . Anti-HCV reagente . HCV-RNA detectável- Menção de hepatite C em qualquer um dos campos da declaração de óbito ou após investigação do óbito por hepatite sem etiologia especificada.Hepatite D: - Caso confirmado de Hepatite B, com pelo menos um dos marcadores a seguir: . Anti-HDV total reagente . HDV-RNA detectável- Menção de hepatite D em qualquer um dos campos da declaração de óbito ou após investigação do óbito por hepatite sem etiologia especificada.Hepatite E: - Indivíduo que apresente um ou mais dos marcadores reagentes ou exame de biologia molecular para hepatite E a seguir: . Anti-HEV IgM e anti-HEV IgG reagentes . HEV-RNA detectável- Menção de hepatite E em qualquer um dos campos da declaração de óbito ou após investigação do óbito por hepatite sem etiologia especificada.`,
  sections,
})
