import { z } from "zod"

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional()

const sections = [
  {
    id: "case_identification",
    title: "Identificação do Caso",
    description: "Dados iniciais da notificação, unidade notificadora e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "dt_filling",
        label: "Data do preenchimento",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de registro",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de registro",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de registro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde de identificação",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (CNES) da Unidade de Saúde",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_symptoms_start",
        label: "Data dos Primeiros Sintomas",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "mother_name",
        label: "Nome da Mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "medical_history",
    title: "Antecedentes e Sinais Clínicos",
    description: "Histórico de vacinação, sinais, sintomas e fatores de risco do paciente.",
    columns: 3,
    fields: [
      {
        name: "st_flu_vaccine",
        label: "Recebeu Vacina contra Gripe nos últimos doze meses?",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_last_vaccine_dose",
        label: "Data da última dose",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "symptom_fever", label: "Febre", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_cough", label: "Tosse", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_sore_throat", label: "Dor de Garganta", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_dyspnea", label: "Dispneia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_myalgia", label: "Mialgia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_o2_saturation", label: "Saturação de O2 menor que 95%", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_respiratory_distress", label: "Desconforto respiratório", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      {
        name: "ds_other_symptoms",
        label: "Outros sinais e sintomas importantes",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "risk_pneumopathy", label: "Pneumopatias Crônicas", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_cardiovascular", label: "Doença Cardiovascular Crônica", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_immunodeficiency", label: "Imunodeficiência/Imunodepressão", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_hepatopathy", label: "Doença Hepática Crônica", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_neuropathy", label: "Doença Neurológica Crônica", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_nephropathy", label: "Doença Renal Crônica", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_down_syndrome", label: "Síndrome de Down", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_diabetes", label: "Diabetes Mellitus", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_puerperium", label: "Puerpério (até quarenta e dois dias do parto)", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "risk_obesity", label: "Obesidade", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      {
        name: "nu_imc",
        label: "IMC",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_other_risks",
        label: "Outros fatores de risco relacionados com a SRAG",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "hospitalization_details",
    title: "Histórico da Internação",
    description: "Informações sobre o uso de antivirais, exames de imagem e dados hospitalares.",
    columns: 3,
    fields: [
      {
        name: "tp_antiviral",
        label: "Uso de antiviral",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Não usou", value: "1" },
          { label: "Oseltamivir", value: "2" },
          { label: "Zanamivir", value: "3" },
          { label: "Outro", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_antiviral_start",
        label: "Data de início do tratamento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_hospitalization",
        label: "Ocorreu internação?",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_hospitalization",
        label: "Data da internação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_uf",
        label: "UF da unidade de internação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city",
        label: "Município da unidade de internação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city_ibge_code",
        label: "Código (IBGE) do Município de internação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_name",
        label: "Nome da unidade de saúde da internação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_code",
        label: "Código (CNES) da unidade de internação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_chest_xray",
        label: "Raio X de Tórax",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Normal", value: "1" },
          { label: "Infiltrado intersticial", value: "2" },
          { label: "Consolidação", value: "3" },
          { label: "Misto", value: "4" },
          { label: "Outro", value: "5" },
          { label: "Não realizado", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_chest_xray",
        label: "Data do Raio X",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_ventilatory_support",
        label: "Fez uso de suporte ventilatório?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Não usou", value: "1" },
          { label: "Sim, invasivo", value: "2" },
          { label: "Sim, não invasivo", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_uti",
        label: "Foi Internado em Unidade de Terapia Intensiva?",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_uti_entrance",
        label: "Data de entrada na UTI",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_uti_exit",
        label: "Data de saída na UTI",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "lab_investigation",
    title: "Dados Laboratoriais",
    description: "Amostras coletadas, metodologias e diagnósticos etiológicos detalhados.",
    columns: 3,
    fields: [
      {
        name: "tp_sample",
        label: "Coletou que tipo de amostra?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Não coletou", value: "1" },
          { label: "Secreção de oro e nasofaringe", value: "2" },
          { label: "Tecido post-mortem", value: "3" },
          { label: "Lavado Bronco-alveolar", value: "4" },
          { label: "Outro", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_sample_collection",
        label: "Data da Coleta",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "method_rt_pcr", label: "Metodologia realizada: RT-PCR", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "method_ifi", label: "Metodologia realizada: IFI", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "method_other", label: "Metodologia realizada: Outro método", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      {
        name: "ds_method_other_spec",
        label: "Especifique o outro método",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_rt_pcr",
        label: "Tipo de RT-PCR",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Convencional", value: "1" },
          { label: "Em tempo real", value: "2" },
        ],
      },
      {
        name: "dt_result_ifi",
        label: "Data do Resultado - IFI",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_result_rt_pcr",
        label: "Data do Resultado - RT-PCR",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_result_other",
        label: "Data do Resultado do outro método",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "result_influenza_a",
        label: "Diagnóstico Etiológico: Influenza A",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "tp_influenza_a_subtipo",
        label: "Subtipo se positivo para Influenza A",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Influenza A(H1N1)pdm09", value: "1" },
          { label: "Influenza A/H1 sazonal", value: "2" },
          { label: "Influenza A/H3 sazonal", value: "3" },
          { label: "Influenza A não subtipado", value: "4" },
          { label: "Influenza A/H3N2v", value: "5" },
          { label: "Outro subtipo de Influenza A", value: "6" },
        ],
      },
      {
        name: "ds_influenza_a_subtipo_other",
        label: "Especifique o outro subtipo de Influenza A",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "result_influenza_b",
        label: "Diagnóstico Etiológico: Influenza B",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "result_vsr",
        label: "Outros agentes: Vírus Sincicial Respiratório (VSR)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "result_parainfluenza_1",
        label: "Outros agentes: Parainfluenza 1",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "result_parainfluenza_2",
        label: "Outros agentes: Parainfluenza 2",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "result_parainfluenza_3",
        label: "Outros agentes: Parainfluenza 3",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "result_adenovirus",
        label: "Outros agentes: Adenovírus",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "result_other_agent",
        label: "Outros agentes: Outro vírus ou agente etiológico",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Inconclusivo", value: "3" },
          { label: "Não realizado", value: "4" },
        ],
      },
      {
        name: "ds_other_agent_spec",
        label: "Especifique o outro vírus ou agente etiológico",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "case_conclusion",
    title: "Conclusão",
    description: "Classificação final do agravo e encerramento epidemiológico.",
    columns: 3,
    fields: [
      {
        name: "tp_final_classification",
        label: "Classificação final da SRAG",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "SRAG por Influenza", value: "1" },
          { label: "SRAG por outros vírus respiratórios", value: "2" },
          { label: "SRAG por outros agentes etiológicos", value: "3" },
          { label: "SRAG não especificada", value: "4" },
        ],
      },
      {
        name: "ds_final_classification_other",
        label: "Especifique os outros agentes etiológicos",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_confirmation_criterion",
        label: "Critério de Confirmação",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico-Epidemiológico", value: "2" },
          { label: "Clínico", value: "3" },
        ],
      },
      {
        name: "tp_evolution",
        label: "Evolução clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Recebeu alta por cura", value: "1" },
          { label: "Evoluiu para óbito", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_discharge_or_death",
        label: "Data da alta ou óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const sragNotificationDefinition = defineNotificationType({
  id: 50,
  slug: "srag",
  label: "Síndrome Respiratória Aguda Grave",
  description: `Vigilância de Influenza por meio de SRAG-Internada ou Óbito por SRAG: indivíduo de qualquer idade, internado com Síndrome Gripal e que apresente Dispneia OU Saturação de O2 <95% OU Desconforto Respiratório.`,
  sections,
})
