import { z } from "zod";

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "INTOXICAÇÃO EXÓGENA",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "T 65.9",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_symptoms_start",
        label: "Data dos Primeiros Sintomas",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "exposure_data",
    title: "Antecedentes e Dados da Exposição",
    description: "Informações sobre a ocupação e o local onde ocorreu a exposição ao agente.",
    columns: 3,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_market_situation",
        label: "Situação no Mercado de Trabalho",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Empregado registrado com carteira assinada", value: "01" },
          { label: "Empregado não registrado", value: "02" },
          { label: "Autônomo/conta própria", value: "03" },
          { label: "Servidor público estatuário", value: "04" },
          { label: "Servidor público celetista", value: "05" },
          { label: "Aposentado", value: "06" },
          { label: "Desempregado", value: "07" },
          { label: "Trabalho temporário", value: "08" },
          { label: "Cooperativado", value: "09" },
          { label: "Trabalhador avulso", value: "10" },
          { label: "Empregador", value: "11" },
          { label: "Outros", value: "12" },
          { label: "Ignorado", value: "99" },
        ],
      },
      {
        name: "tp_exposure_place",
        label: "Local de ocorrência da exposição",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Residência", value: "1" },
          { label: "Ambiente de trabalho", value: "2" },
          { label: "Trajeto do trabalho", value: "3" },
          { label: "Serviços de saúde", value: "4" },
          { label: "Escola/creche", value: "5" },
          { label: "Ambiente externo", value: "6" },
          { label: "Outro", value: "7" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_exposure_place_name",
        label: "Nome do local/estabelecimento de ocorrência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "co_cnae",
        label: "Atividade Econômica (CNAE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_uf",
        label: "UF do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_city",
        label: "Município do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_city_ibge_code",
        label: "Código (IBGE) do Município do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_district",
        label: "Distrito do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_neighborhood",
        label: "Bairro do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_street",
        label: "Logradouro do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_number",
        label: "Número do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_complement",
        label: "Complemento do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_reference_point",
        label: "Ponto de Referência do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_zipcode",
        label: "CEP do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "exposure_phone",
        label: "Telefone do estabelecimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_exposure_zone",
        label: "Zona de exposição",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "exposure_country",
        label: "País (se estabelecimento fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "agent_exposure_details",
    title: "Dados do Agente Tóxico e da Exposição",
    description: "Identificação das substâncias químicas, vias e circunstâncias da contaminação.",
    columns: 2,
    fields: [
      {
        name: "tp_toxic_agent_group",
        label: "Grupo do agente tóxico / Classificação geral",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Medicamento", value: "01" },
          { label: "Agrotóxico; uso agrícola", value: "02" },
          { label: "Agrotóxico / uso doméstico", value: "03" },
          { label: "Agrotóxico / uso saúde pública", value: "04" },
          { label: "Raticida", value: "05" },
          { label: "Produto veterinário", value: "06" },
          { label: "Produto de uso Domiciliar", value: "07" },
          { label: "Cosmético / higiene pessoal", value: "08" },
          { label: "Produto químico de uso industrial", value: "09" },
          { label: "Metal", value: "10" },
          { label: "Drogas de abuso", value: "11" },
          { label: "Planta tóxica", value: "12" },
          { label: "Alimento e bebida", value: "13" },
          { label: "Outro", value: "14" },
          { label: "Ignorado", value: "99" },
        ],
      },
      { name: "ds_agent_1_brand", label: "Nome Comercial / Popular (Agente 1)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "ds_agent_1_active", label: "Princípio Ativo (Agente 1)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "ds_agent_2_brand", label: "Nome Comercial / Popular (Agente 2)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "ds_agent_2_active", label: "Princípio Ativo (Agente 2)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "ds_agent_3_brand", label: "Nome Comercial / Popular (Agente 3)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "ds_agent_3_active", label: "Princípio Ativo (Agente 3)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      {
        name: "tp_pesticide_purpose",
        label: "Se agrotóxico, qual a finalidade da utilização",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Inseticida", value: "1" },
          { label: "Herbicida", value: "2" },
          { label: "Carrapaticida", value: "3" },
          { label: "Raticida", value: "4" },
          { label: "Fungicida", value: "5" },
          { label: "Preservante para madeira", value: "6" },
          { label: "Outro", value: "7" },
          { label: "Não se aplica", value: "8" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_pesticide_activity_1",
        label: "Atividades exercidas na exposição atual (Primeira opção)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Diluição", value: "01" },
          { label: "Pulverização", value: "02" },
          { label: "Tratamento de sementes", value: "03" },
          { label: "Armazenagem", value: "04" },
          { label: "Colheita", value: "05" },
          { label: "Transporte", value: "06" },
          { label: "Desinsetização", value: "07" },
          { label: "Produção / formulação", value: "08" },
          { label: "Outros", value: "09" },
          { label: "Não se aplica", value: "10" },
          { label: "Ignorado", value: "99" },
        ],
      },
      {
        name: "tp_pesticide_activity_2",
        label: "Atividades exercidas na exposição atual (Segunda opção)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Diluição", value: "01" },
          { label: "Pulverização", value: "02" },
          { label: "Tratamento de sementes", value: "03" },
          { label: "Armazenagem", value: "04" },
          { label: "Colheita", value: "05" },
          { label: "Transporte", value: "06" },
          { label: "Desinsetização", value: "07" },
          { label: "Produção / formulação", value: "08" },
          { label: "Outros", value: "09" },
          { label: "Não se aplica", value: "10" },
          { label: "Ignorado", value: "99" },
        ],
      },
      {
        name: "tp_pesticide_activity_3",
        label: "Atividades exercidas na exposição atual (Terceira opção)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Diluição", value: "01" },
          { label: "Pulverização", value: "02" },
          { label: "Tratamento de sementes", value: "03" },
          { label: "Armazenagem", value: "04" },
          { label: "Colheita", value: "05" },
          { label: "Transporte", value: "06" },
          { label: "Desinsetização", value: "07" },
          { label: "Produção / formulação", value: "08" },
          { label: "Outros", value: "09" },
          { label: "Não se aplica", value: "10" },
          { label: "Ignorado", value: "99" },
        ],
      },
      {
        name: "ds_pesticide_culture",
        label: "Se agrotóxico de uso agrícola, qual a cultura / lavoura",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_exposure_route_1",
        label: "Via de exposição / contaminação (Primeira opção)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Digestiva", value: "1" },
          { label: "Cutânea", value: "2" },
          { label: "Respiratória", value: "3" },
          { label: "Ocular", value: "4" },
          { label: "Parenteral", value: "5" },
          { label: "Vaginal", value: "6" },
          { label: "Transplacentária", value: "7" },
          { label: "Outra", value: "8" },
          { label: "Ignorada", value: "9" },
        ],
      },
      {
        name: "tp_exposure_route_2",
        label: "Via de exposição / contaminação (Segunda opção)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Digestiva", value: "1" },
          { label: "Cutânea", value: "2" },
          { label: "Respiratória", value: "3" },
          { label: "Ocular", value: "4" },
          { label: "Parenteral", value: "5" },
          { label: "Vaginal", value: "6" },
          { label: "Transplacentária", value: "7" },
          { label: "Outra", value: "8" },
          { label: "Ignorada", value: "9" },
        ],
      },
      {
        name: "tp_exposure_route_3",
        label: "Via de exposição / contaminação (Terceira opção)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Digestiva", value: "1" },
          { label: "Cutânea", value: "2" },
          { label: "Respiratória", value: "3" },
          { label: "Ocular", value: "4" },
          { label: "Parenteral", value: "5" },
          { label: "Vaginal", value: "6" },
          { label: "Transplacentária", value: "7" },
          { label: "Outra", value: "8" },
          { label: "Ignorada", value: "9" },
        ],
      },
      {
        name: "tp_exposure_circumstance",
        label: "Circunstância da exposição / contaminação",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Uso Habitual", value: "01" },
          { label: "Acidental", value: "02" },
          { label: "Ambiental", value: "03" },
          { label: "Uso terapêutico", value: "04" },
          { label: "Prescrição médica inadequada", value: "05" },
          { label: "Erro de administração", value: "06" },
          { label: "Automedicação", value: "07" },
          { label: "Abuso", value: "08" },
          { label: "Ingestão de alimento ou bebida", value: "09" },
          { label: "Tentativa de suicídio", value: "10" },
          { label: "Tentativa de aborto", value: "11" },
          { label: "Violência / homicídio", value: "12" },
          { label: "Outra", value: "13" },
          { label: "Ignorado", value: "99" },
        ],
      },
      {
        name: "st_work_related_exposure",
        label: "A exposição / contaminação foi decorrente do trabalho / ocupação?",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_exposure_type",
        label: "Tipo de Exposição",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Aguda única", value: "1" },
          { label: "Aguda repetida", value: "2" },
          { label: "Crônica", value: "3" },
          { label: "Aguda sobre Crônica", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "nu_time_exposure_attendance",
        label: "Tempo Decorrido entre a Exposição e o Atendimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_time_exposure_attendance_unit",
        label: "Unidade do Tempo Decorrido",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_attendance",
        label: "Tipo de atendimento",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Hospitalar", value: "1" },
          { label: "Ambulatorial", value: "2" },
          { label: "Domiciliar", value: "3" },
          { label: "Nenhum", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "hospitalization_conclusion",
    title: "Dados do Atendimento e Conclusão do Caso",
    description: "Informações sobre internação, diagnóstico clínico e evolução final do paciente.",
    columns: 3,
    fields: [
      {
        name: "st_hospitalization",
        label: "Houve hospitalização?",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_hospitalization",
        label: "Data da internação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_uf",
        label: "UF de hospitalização",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city",
        label: "Município de hospitalização",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city_ibge_code",
        label: "Código (IBGE) do Município de hospitalização",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_name",
        label: "Unidade de saúde",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_code",
        label: "Código da Unidade de saúde",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_final_classification",
        label: "Classificação final",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Intoxicação confirmada", value: "1" },
          { label: "Só Exposição", value: "2" },
          { label: "Reação Adversa", value: "3" },
          { label: "Outro Diagnóstico", value: "4" },
          { label: "Síndrome de abstinência", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "co_diagnostic_cid10",
        label: "Se intoxicação confirmada, qual o diagnóstico (CID-10)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_confirmation_criterion",
        label: "Critério de confirmação",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico-epidemiológico", value: "2" },
          { label: "Clínico", value: "3" },
        ],
      },
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Cura sem sequela", value: "1" },
          { label: "Cura com sequela", value: "2" },
          { label: "Óbito por intoxicação exógena", value: "3" },
          { label: "Óbito por outra causa", value: "4" },
          { label: "Perda de seguimento", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_cat",
        label: "Comunicação de Acidente de Trabalho - CAT",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não se aplica", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const exogenousPoisoningNotificationDefinition = defineNotificationType({
  id: 60,
  slug: "intoxicacao-exogena",
  label: "Intoxicação Exógena",
  description: `Caso suspeito: todo aquele indivíduo que, tendo sido exposto a substâncias químicas, apresente sinais e sintomas clínicos de intoxicação e/ou alterações laboratoriais provavelmente ou possivelmente compatíveis.`,
  sections,
})
