import { z } from "zod";

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();
const optionalNumberSchema = z.number().optional();

const serologyOptions = [
  { label: "Reagente", value: "1" },
  { label: "Não Reagente", value: "2" },
  { label: "Inconclusivo", value: "3" },
  { label: "Não Realizado", value: "4" },
];

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
        options: [
          { label: "Sarampo", value: "1" },
          { label: "Rubéola", value: "2" },
        ],
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "B09",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_symptoms_start",
        label: "Data dos Primeiros Sintomas",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "epidemiological_history",
    title: "Antecedentes Epidemiológicos",
    description: "Histórico vacinal e mapeamento de contatos epidemiológicos recentes.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_vaccinated",
        label: "Tomou Vacina Contra Sarampo e Rubéola (dupla ou triviral)",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_last_vaccine_dose",
        label: "Data da Última Dose",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_contact_history",
        label: "Contato Com Caso Suspeito ou Confirmado de Sarampo ou Rubéola",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Domicílio", value: "1" },
          { label: "Vizinhança", value: "2" },
          { label: "Trabalho", value: "3" },
          { label: "Creche/Escola", value: "4" },
          { label: "Posto de Saúde/Hospital", value: "5" },
          { label: "Outro Estado/Município", value: "6" },
          { label: "Sem História de Contato", value: "7" },
          { label: "Outro país", value: "8" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_contact_name",
        label: "Nome do Contato",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_contact_address",
        label: "Endereço do contato",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "clinical_data",
    title: "Dados Clínicos",
    description: "Sinais, sintomas, manifestações clínicas exantemáticas e dados de internação.",
    columns: 3,
    fields: [
      {
        name: "dt_exanthema_start",
        label: "Data do Início do Exantema",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_fever_start",
        label: "Data do Início da Febre",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "symptom_cough", label: "Tosse", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_coryza", label: "Coriza", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_conjunctivitis", label: "Conjuntivite", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_arthralgia_arthritis", label: "Artralgia/Artrite (dores nas juntas)", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_ganglions", label: "Presença de Gânglios Retroauriculares/Occipitais", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_retro_ocular_pain", label: "Dor Retro-Ocular", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      {
        name: "st_hospitalization",
        label: "Ocorreu Hospitalização",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "dt_hospitalization",
        label: "Data da Internação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_uf",
        label: "UF do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city",
        label: "Município do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_city_ibge_code",
        label: "Código (IBGE) do @Município do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_name",
        label: "Nome do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "hospital_code",
        label: "Código do Hospital",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "lab_investigation",
    title: "Dados do Laboratório",
    description: "Investigação laboratorial sorológica e isolamento viral para confirmação etiológica.",
    columns: 3,
    fields: [
      {
        name: "dt_collection_s1",
        label: "Data da Coleta da Primeira Amostra (S1)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_collection_s2",
        label: "Data da Coleta da Segunda Amostra (S2)",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "serology_measles_igm_s1", label: "Sarampo IgM: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igg_s1", label: "Sarampo IgG: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igm_s2", label: "Sarampo IgM: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igg_s2", label: "Sarampo IgG: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igm_retest", label: "Sarampo IgM: Re-Teste", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igg_retest", label: "Sarampo IgG: Re-Teste", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_rubella_igm_s1", label: "Rubéola IgM: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_rubella_igg_s1", label: "Rubéola IgG: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_rubella_igm_s2", label: "Rubéola IgM: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_rubella_igg_s2", label: "Rubéola IgG: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_rubella_igm_retest", label: "Rubéola IgM: Re-Teste", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_rubella_igg_retest", label: "Rubéola IgG: Re-Teste", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_other_igm_s1", label: "Outras Exantemáticas IgM: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_other_igg_s1", label: "Outras Exantemáticas IgG: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_other_igm_s2", label: "Outras Exantemáticas IgM: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_other_igg_s2", label: "Outras Exantemáticas IgG: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_other_igm_retest", label: "Outras Exantemáticas IgM: Re-Teste", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_other_igg_retest", label: "Outras Exantemáticas IgG: Re-Teste", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      {
        name: "tp_other_exanthematic_virus",
        label: "Vírus de outras exantemáticas investigado",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Dengue", value: "1" },
          { label: "Parvovírus B19", value: "2" },
          { label: "Herpes vírus 6", value: "3" },
          { label: "Outras", value: "4" },
        ],
      },
      {
        name: "st_viral_isolation_collected",
        label: "Amostra clínica coletada para Isolamento Viral",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_viral_isolation_sample",
        label: "Tipo de amostra clínica coletada para Isolamento Viral",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sangue Total", value: "1" },
          { label: "Secreção Nasofaríngea", value: "2" },
          { label: "Urina", value: "3" },
          { label: "Líquor", value: "4" },
        ],
      },
      {
        name: "tp_viral_etiology",
        label: "Etiologia Viral identificada",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Vírus Sarampo Selvagem", value: "1" },
          { label: "Vírus Sarampo Vacinal", value: "2" },
          { label: "Vírus Rubéola Selvagem", value: "3" },
          { label: "Vírus Rubéola Vacinal", value: "4" },
          { label: "Dengue", value: "5" },
          { label: "Herpes Vírus Tipo 6", value: "6" },
          { label: "Parvovírus B19", value: "7" },
          { label: "Enterovírus", value: "8" },
          { label: "Outras", value: "9" },
          { label: "Não detectado", value: "10" },
        ],
      },
    ],
  },
  {
    id: "control_measures",
    title: "Medidas de Controle",
    description: "Bloqueio vacinal e monitoramento epidemiológico.",
    columns: 2,
    fields: [
      {
        name: "st_vaccinal_block",
        label: "Realizou Bloqueio Vacinal",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não, todos vacinados", value: "3" },
          { label: "Não, sem história de contato", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "nu_vaccinated_under_5",
        label: "Pessoas vacinadas menores de cinco anos",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "nu_vaccinated_5_to_14",
        label: "Pessoas vacinadas de cinco a quatorze anos",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "nu_vaccinated_15_to_39",
        label: "Pessoas vacinadas de quinze a trinta e nove anos",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "tp_block_time_interval",
        label: "Especifique o Intervalo de Tempo do bloqueio vacinal",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Em até setenta e duas horas", value: "1" },
          { label: "Após setenta e duas horas", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "travel_history",
    title: "Deslocamento",
    description: "Histórico de viagens nos 7 a 23 dias anteriores ao início dos sintomas.",
    columns: 3,
    fields: [
      {
        name: "dt_travel",
        label: "Data do Deslocamento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "travel_uf",
        label: "UF de Deslocamento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "travel_city",
        label: "Município de Deslocamento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "travel_country",
        label: "País de Deslocamento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_travel_transport",
        label: "Meio de Transporte Utilizado",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "case_conclusion",
    title: "Conclusão do Caso",
    description: "Classificação final do agravo, critérios e encerramento do caso.",
    columns: 3,
    fields: [
      {
        name: "tp_final_classification",
        label: "Classificação Final",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sarampo", value: "1" },
          { label: "Rubéola", value: "2" },
          { label: "Descartado", value: "3" },
        ],
      },
      {
        name: "tp_confirmation_criterion",
        label: "Critério de Confirmação ou Descarte",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico-epidemiológico", value: "2" },
          { label: "Clínico", value: "3" },
          { label: "Data da Última Dose da Vacina", value: "4" },
        ],
      },
      {
        name: "tp_discarded_classification",
        label: "Classificação final do caso descartado",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Dengue", value: "1" },
          { label: "Escarlatina", value: "2" },
          { label: "Exantema Súbito (Herpes Vírus Tipo 6)", value: "3" },
          { label: "Eritema Infeccioso (Parvovírus B19)", value: "4" },
          { label: "Enterovirose", value: "5" },
          { label: "Evento Temporal Relacionado à Vacina", value: "6" },
          { label: "IgM associado temporalmente à vacina", value: "7" },
          { label: "Sem soroconversão dos anticorpos IgG", value: "8" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "lpi_is_autochthonous",
        label: "O caso é autóctone do município de residência?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Indeterminado", value: "3" },
        ],
      },
      {
        name: "lpi_uf",
        label: "UF LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_country",
        label: "País LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_city",
        label: "Município LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_city_ibge_code",
        label: "Código (IBGE) do Município LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_district",
        label: "Distrito LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "lpi_neighborhood",
        label: "Bairro LPI",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Cura", value: "1" },
          { label: "Óbito por doenças exantemáticas", value: "2" },
          { label: "Óbito por outras causas", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const exanthematicFeversNotificationDefinition = defineNotificationType({
  id: 70,
  slug: "doencas-exantematicas",
  label: "Doenças Exantemáticas Febris",
  description: `CASO SUSPEITO DE SARAMPO: Todo paciente que apresentar febre e exantema maculopapular, acompanhados de um ou maisdos seguintes sinais e sintomas: tosse e/ou coriza e/ou conjuntivite, independente da idade e da situação vacinal.CASO SUSPEITO DE RUBÉOLA: Todo paciente que apresente febre e exantema maculopapular, acompanhado delinfoadenopatia retroaurícular, occipital e cervical, independente da idade e da situação vacinal.`,
  sections,
})
