import { z } from "zod";

import {
  defineNotificationType,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();
const optionalNumberSchema = z.number().optional();

const timeUnitOptions = [
  { label: "Horas", value: "1" },
  { label: "Dias", value: "2" },
];

const establishmentPlaceOptions = [
  { label: "Ambulantes", value: "01" },
  { label: "Comemorações", value: "02" },
  { label: "Creche / Escola", value: "03" },
  { label: "Hospital / Unidade de Saúde", value: "04" },
  { label: "Indústria", value: "05" },
  { label: "Lanchonete / Confeitaria / Padaria", value: "06" },
  { label: "Produção Agropecuária", value: "07" },
  { label: "Refeitório", value: "08" },
  { label: "Residência", value: "09" },
  { label: "Restaurante", value: "10" },
  { label: "Outros", value: "11" },
  { label: "Ignorado", value: "99" },
];

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação de surto e unidade notificadora.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("3"),
        defaultValue: "3",
        options: [{ label: "Surto", value: "3" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "SURTO - DOENÇAS TRANSMITIDAS POR ALIMENTOS",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "A05.9",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do @Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "outbreak_notification",
    title: "Notificação de Surto",
    description: "Dados temporais, quantitativos e o local inicial do surto.",
    columns: 3,
    fields: [
      {
        name: "dt_first_case_symptoms",
        label: "Data dos Sintomas do Primeiro Caso Suspeito",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "nu_suspect_exposed_cases",
        label: "Número de Casos Suspeitos / Expostos até a Data da Notificação",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "tp_initial_occurrence_place",
        label: "Local Inicial de Ocorrência do Surto",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
        options: [
          { label: "Residência", value: "1" },
          { label: "Hospital / Unidade de Saúde", value: "2" },
          { label: "Creche / Escola", value: "3" },
          { label: "Asilo", value: "4" },
          { label: "Outras Instituições (alojamento, trabalho)", value: "5" },
          { label: "Restaurante / Padaria (similares)", value: "6" },
          { label: "Eventos", value: "7" },
          { label: "Casos Dispersos no Bairro", value: "8" },
          { label: "Casos Dispersos Pelo Município", value: "9" },
          { label: "Casos Dispersos em mais de um Município", value: "10" },
          { label: "Outros", value: "11" },
        ],
      },
      {
        name: "ds_initial_occurrence_place_spec",
        label: "Especificar outro local inicial de ocorrência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "occurrence_location",
    title: "Dados de Ocorrência",
    description: "Localização geográfica detalhada onde o surto foi identificado.",
    columns: 3,
    fields: [
      {
        name: "occurrence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "occurrence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "occurrence_city_ibge_code",
        label: "Código (IBGE) do Município de Ocorrência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "occurrence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "epidemiological_investigation",
    title: "Investigação Epidemiológica - DTA",
    description: "Dados da consolidação das entrevistas e impacto clínico do surto.",
    columns: 3,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_transmission_mode",
        label: "Modo Provável da Transmissão",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Direta (pessoa a pessoa)", value: "1" },
          { label: "Indireta (Veículo comum ou Vetor)", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_transmission_vehicle",
        label: "Veículo de Transmissão",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Alimento / Água", value: "1" },
        ],
      },
      {
        name: "nu_interviewed",
        label: "Número de Entrevistados",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "nu_sick_interviewed",
        label: "Número de Doentes Entrevistados",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "nu_total_sick",
        label: "Número Total de Doentes",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "nu_total_hospitalized",
        label: "Número Total de Hospitalizados",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "nu_total_deaths",
        label: "Número de Óbitos",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
    ],
  },
  {
    id: "signs_symptoms_and_incubation",
    title: "Manifestações Clínicas e Período de Incubação",
    description: "Sinais clínicos consolidados no grupo de doentes e tempos médios de incubação.",
    columns: 3,
    fields: [
      { name: "symptom_nausea", label: "Náuseas", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_vomiting", label: "Vômitos", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_diarrhea", label: "Diarréia", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_headache", label: "Cefaléia", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_abdominal_pain", label: "Dor Abdominal", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_neurological", label: "Neurológicos", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_fever", label: "Febre", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "symptom_other", label: "Outros", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      {
        name: "nu_incubation_period_min",
        label: "Período de Incubação Mínimo",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_incubation_period_min_unit",
        label: "Unidade do Período Mínimo",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: timeUnitOptions,
      },
      {
        name: "nu_incubation_period_max",
        label: "Período de Incubação Máximo",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_incubation_period_max_unit",
        label: "Unidade do Período Máximo",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: timeUnitOptions,
      },
      {
        name: "nu_incubation_period_median",
        label: "Mediana do Período de Incubação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_incubation_period_median_unit",
        label: "Unidade da Mediana",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: timeUnitOptions,
      },
    ],
  },
  {
    id: "causal_factors_and_places",
    title: "Fatores Causais e Cadeia Alimentar",
    description: "Hipóteses de falhas no preparo e locais de produção e consumo dos alimentos.",
    columns: 2,
    fields: [
      { name: "factor_raw_material", label: "Fatores causais: Matéria-prima Imprópria", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "factor_conservation", label: "Fatores causais: Conservação Inadequada", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "factor_preparation", label: "Fatores causais: Manipulação / Preparação Inadequada", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      { name: "factor_other", label: "Fatores causais: Outros", kind: "select", schema: z.string(), defaultValue: "2", options: yesNoUnknownOptions },
      {
        name: "ds_factor_other_spec",
        label: "Especificar outros fatores causais",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_production_place",
        label: "Local de Produção / Preparação",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: establishmentPlaceOptions,
      },
      {
        name: "ds_production_place_spec",
        label: "Especificar outro local de produção",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_ingestion_place",
        label: "Local de Ingestão",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: establishmentPlaceOptions,
      },
      {
        name: "ds_ingestion_place_spec",
        label: "Especificar outro local de ingestão",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "laboratory_samples",
    title: "Amostras Laboratoriais",
    description: "Coleta e resultados analíticos de amostras clínicas e bromatológicas.",
    columns: 3,
    fields: [
      {
        name: "st_clinical_samples",
        label: "Coletadas Amostras Clínicas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "nu_clinical_samples",
        label: "Número de Amostras Clínicas",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      { name: "ds_clinical_result_1", label: "Resultado Clínico 1 (Principal Achado)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "nu_clinical_positive_1", label: "Número de Positivas (Resultado 1)", kind: "number", schema: optionalNumberSchema, defaultValue: 0 },
      { name: "ds_clinical_result_2", label: "Resultado Clínico 2 (Outro Achado)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "nu_clinical_positive_2", label: "Número de Positivas (Resultado 2)", kind: "number", schema: optionalNumberSchema, defaultValue: 0 },
      { name: "ds_clinical_result_3", label: "Resultado Clínico 3 (Outro Achado)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "nu_clinical_positive_3", label: "Número de Positivas (Resultado 3)", kind: "number", schema: optionalNumberSchema, defaultValue: 0 },
      {
        name: "st_bromatological_samples",
        label: "Coletadas Amostras de Alimentos",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "nu_bromatological_samples",
        label: "Número de Amostras de Alimentos",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      { name: "ds_bromatological_result_1", label: "Resultado Bromatológico 1 (Principal Achado)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "nu_bromatological_positive_1", label: "Número de Positivas (Bromatológico 1)", kind: "number", schema: optionalNumberSchema, defaultValue: 0 },
      { name: "ds_bromatological_result_2", label: "Resultado Bromatológico 2 (Outro Achado)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "nu_bromatological_positive_2", label: "Número de Positivas (Bromatológico 2)", kind: "number", schema: optionalNumberSchema, defaultValue: 0 },
      { name: "ds_bromatological_result_3", label: "Resultado Bromatológico 3 (Outro Achado)", kind: "text", schema: optionalTextSchema, defaultValue: "" },
      { name: "nu_bromatological_positive_3", label: "Número de Positivas (Bromatológico 3)", kind: "number", schema: optionalNumberSchema, defaultValue: 0 },
    ],
  },
  {
    id: "case_conclusion",
    title: "Conclusão e Encerramento",
    description: "Agente etiológico conclusivo, alimento causador do surto e ações adotadas.",
    columns: 3,
    fields: [
      {
        name: "ds_outbreak_etiological_agent",
        label: "Agente Etiológico do Surto (Gênero e Espécie)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_causal_food",
        label: "Alimento causador do surto",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_confirmation_criterion",
        label: "Critério de Confirmação (Referente ao Agente)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Clínico-Epidemiológico", value: "1" },
          { label: "Laboratorial Clínico", value: "2" },
          { label: "Laboratorial Bromatológico", value: "3" },
          { label: "Laboratorial Clínico Bromatológico", value: "4" },
          { label: "Inconclusivo", value: "5" },
        ],
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_measures_adopted",
        label: "Medidas Adotadas / Recomendadas",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const dtaOutbreakNotificationDefinition = defineNotificationType({
  id: 120,
  slug: "surto-dta",
  label: "Investigação de Surto - DTA",
  description: `Ficha de notificação e acompanhamento para investigação epidemiológica de surtos de Doenças Transmitidas por Alimentos (DTA) no padrão SINAN.`,
  sections,
})
