import { z } from "zod";

import {
  defineNotificationType,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();
const optionalNumberSchema = z.number().optional();

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação de surto e unidade notificadora.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("3"),
        defaultValue: "3",
        options: [{ label: "Surto", value: "3" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "outbreak_notification",
    title: "Notificação de Surto",
    description: "Dados temporais, quantitativos e o local inicial do surto.",
    columns: 3,
    fields: [
      {
        name: "dt_first_case_symptoms",
        label: "Data dos Sintomas do Primeiro Caso Suspeito",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "nu_suspect_exposed_cases",
        label: "Número de Casos Suspeitos / Expostos até a Data da Notificação",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "tp_initial_occurrence_place",
        label: "Local Inicial de Ocorrência do Surto",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
        options: [
          { label: "Residência", value: "1" },
          { label: "Hospital / Unidade de Saúde", value: "2" },
          { label: "Creche / Escola", value: "3" },
          { label: "Asilo", value: "4" },
          { label: "Outras Instituições (alojamento, trabalho)", value: "5" },
          { label: "Restaurante / Padaria (similares)", value: "6" },
          { label: "Eventos", value: "7" },
          { label: "Casos Dispersos no Bairro", value: "8" },
          { label: "Casos Dispersos Pelo Município", value: "9" },
          { label: "Casos Dispersos em mais de um Município", value: "10" },
          { label: "Outros", value: "11" },
        ],
      },
      {
        name: "ds_initial_occurrence_place_spec",
        label: "Especificar outro local inicial de ocorrência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "occurrence_location",
    title: "Dados de Ocorrência",
    description: "Localização geográfica detalhada onde o surto foi identificado.",
    columns: 3,
    fields: [
      {
        name: "occurrence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "occurrence_city",
        label: "Município de Residência / Ocorrência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "occurrence_city_ibge_code",
        label: "Código (IBGE) do Município de Ocorrência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "occurrence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "occurrence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "investigation_transmission",
    title: "Dados da Investigação e Transmissão",
    description: "Acompanhamento temporal da investigação e hipóteses de transmissão do agravo.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_transmission_mode",
        label: "Modo Provável da Transmissão",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Direta (pessoa a pessoa)", value: "1" },
          { label: "Indireta (Veículo comum ou Vetor)", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_indirect_transmission_vehicle",
        label: "Se indireta, qual o veículo de transmissão provável",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Alimento / Água", value: "1" },
          { label: "Recursos Hídricos Contaminados (poço, rio, reservatório de água)", value: "2" },
          { label: "Vetor", value: "3" },
          { label: "Produto (medicamentos, agrotóxicos, imunobiológicos, sangue, etc.)", value: "4" },
          { label: "Fômite (faca, lençóis, agulhas, etc.)", value: "5" },
          { label: "Outro", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_indirect_transmission_vehicle_spec",
        label: "Especificar outro veículo de transmissão",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const outbreakNotificationDefinition = defineNotificationType({
  id: 110,
  slug: "surto",
  label: "Investigação de Surto",
  description: `Ficha de notificação e acompanhamento epidemiológico para investigação de surtos conforme diretrizes estabelecidas pelo SINAN.`,
  sections,
})
