import { z } from "zod";

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação da paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "SÍFILIS EM GESTANTE",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "O98.1",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_diagnosis",
        label: "Data do Diagnóstico",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "F",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string().min(1, "Idade gestacional obrigatória"),
        defaultValue: "",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "maternal_history",
    title: "Dados Complementares e Antecedentes Epidemiológicos",
    description: "Mapeamento do acompanhamento de pré-natal e classificação clínica da gestante.",
    columns: 3,
    fields: [
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_uf",
        label: "UF de realização do Pré-Natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_city",
        label: "Município de realização do Pré-Natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_city_ibge_code",
        label: "Código (IBGE) do Município de Pré-Natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_health_unit_code",
        label: "Código da Unidade de realização do pré-natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "nu_sisprenatal",
        label: "Nº da Gestante no SISPRENATAL",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_clinical_classification",
        label: "Classificação Clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Primária", value: "1" },
          { label: "Secundária", value: "2" },
          { label: "Terciária", value: "3" },
          { label: "Latente", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "maternal_laboratorial",
    title: "Resultado dos Exames Laboratoriais",
    description: "Resultados dos testes treponêmicos e não treponêmicos realizados no pré-natal.",
    columns: 3,
    fields: [
      {
        name: "st_non_treponemal_test",
        label: "Teste não treponêmico no pré-natal",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não Reagente", value: "2" },
          { label: "Não Realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_non_treponemal_title",
        label: "Título do teste não treponêmico",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_non_treponemal_test",
        label: "Data do teste não treponêmico",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_treponemal_test",
        label: "Teste treponêmico no pré-natal",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "treatment_and_partner",
    title: "Tratamento e Antecedentes Epidemiológicos da Parceria Sexual",
    description: "Esquema terapêutico prescrito à gestante, acompanhamento e motivos de não tratamento do parceiro.",
    columns: 2,
    fields: [
      {
        name: "tp_maternal_treatment_regimen",
        label: "Esquema de tratamento prescrito à gestante",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Penicilina G benzatina 2.400.000 UI", value: "1" },
          { label: "Penicilina G benzatina 4.800.000 UI", value: "2" },
          { label: "Penicilina G benzatina 7.200.000 UI", value: "3" },
          { label: "Outro esquema", value: "4" },
          { label: "Não realizado", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_partner_treated",
        label: "Parceiro tratado concomitantemente à gestante",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_partner_treatment_regimen",
        label: "Esquema de tratamento prescrito ao parceiro",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Penicilina G benzatina 2.400.000 UI", value: "1" },
          { label: "Penicilina G benzatina 4.800.000 UI", value: "2" },
          { label: "Penicilina G benzatina 7.200.000 UI", value: "3" },
          { label: "Outro esquema", value: "4" },
          { label: "Não realizado", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_partner_not_treated_reason",
        label: "Motivo para o não tratamento do Parceiro",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Parceiro não teve mais contato com a gestante", value: "1" },
          { label: "Parceiro não foi comunicado/convocado à unidade de saúde para tratamento", value: "2" },
          { label: "Parceiro foi comunicado/convocado à unidade de saúde para tratamento, mas não compareceu", value: "3" },
          { label: "Parceiro foi comunicado/convocado à unidade de saúde mas recusou o tratamento", value: "4" },
          { label: "Parceiro com sorologia não reagente", value: "5" },
          { label: "Outro motivo", value: "6" },
        ],
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const pregnantSyphilisNotificationDefinition = defineNotificationType({
  id: 90,
  slug: "sifilis-gestante",
  label: "Sífilis em Gestante",
  description: `Definição de caso:Situação1-Mulherassintomáticaparasífilisque,duranteopré-natal,opartoe/ouopuerpério,apresentepelomenosumtestereagentetreponêmicoE/OUnãotreponêmico,comqualquertitulação,semregistrodetratamentoprévio.Situação2-Mulhersintomáticaaparasífilisque,duranteopré-natal,opartoe/ouopuerpério,apresentepelomenosumtestereagentetreponêmicoE/OUnãotreponêmico,comqualquertitulação.aParamaisinformaçõessobreasintomatologiadasífilis,consultaroGuiadeVigilanciaemSaúdee/ouProtocoloClínicoeDiretrizesTerapêuticasparaAtençãoàsPessoas com Infecções Sexualmente Transmissíveis (IST), disponível respectivamente em www.saude.gov.br/svs e www.aids.gov.br/pcdt.Situação3-Mulherque,duranteopré-natal,opartoe/ouopuerpério,apresentetestenãotreponêmicoreagentecomqualquertitulação E teste treponêmico reagente, independentemente de sintomatologia da sífilis e de tratamento prévio.* Casos confirmados de cicatriz sorológica não devem ser notificados.`,
  sections,
})
