import { z } from "zod";

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "SÍFILIS CONGÊNITA",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "A 50.9",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_diagnosis",
        label: "Data do Diagnóstico",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "6",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "10",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "mother_complements",
    title: "Dados Complementares da Mãe",
    description: "Informações socioeconômicas, histórico de pré-natal e tratamento da gestante.",
    columns: 3,
    fields: [
      {
        name: "mother_age",
        label: "Idade da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_race_color",
        label: "Raça/cor da mãe",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Branca", value: "1" },
          { label: "Preta", value: "2" },
          { label: "Amarela", value: "3" },
          { label: "Parda", value: "4" },
          { label: "Indígena", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "mother_occupation",
        label: "Ocupação da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_education_level",
        label: "Escolaridade da mãe",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Analfabeto", value: "0" },
          { label: "1ª a 4ª série incompleta do EF", value: "1" },
          { label: "4ª série completa do EF", value: "2" },
          { label: "5ª à 8ª série incompleta do EF", value: "3" },
          { label: "Ensino fundamental completo", value: "4" },
          { label: "Ensino médio incompleto", value: "5" },
          { label: "Ensino médio completo", value: "6" },
          { label: "Educação superior incompleta", value: "7" },
          { label: "Educação superior completa", value: "8" },
          { label: "Ignorado", value: "9" },
          { label: "Não se aplica", value: "10" },
        ],
      },
      {
        name: "st_prenatal",
        label: "Realizou Pré-Natal nesta gestação",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: yesNoUnknownOptions,
      },
      {
        name: "prenatal_uf",
        label: "UF de Realização do Pré-Natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_city",
        label: "Município de Realização do Pré-Natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_city_ibge_code",
        label: "Código (IBGE) do Município de Realização do Pré-Natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_health_unit_name",
        label: "Unidade de Saúde de realização do pré-natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "prenatal_health_unit_code",
        label: "Código da Unidade do pré-natal",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_maternal_syphilis_diagnosis",
        label: "Diagnóstico de sífilis materna",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Durante o pré-natal", value: "1" },
          { label: "No momento do parto/curetagem", value: "2" },
          { label: "Após o parto", value: "3" },
          { label: "Não realizado", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_mother_non_treponemal_test",
        label: "Teste não treponêmico no parto/curetagem",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_mother_non_treponemal_title",
        label: "Título do teste não treponêmico",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_mother_non_treponemal",
        label: "Data do teste não treponêmico",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_mother_treponemal_test",
        label: "Teste treponêmico no parto/curetagem",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_mother_treponemal",
        label: "Data do teste treponêmico",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_mother_treatment_regimen",
        label: "Esquema de tratamento da mãe",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Adequado", value: "1" },
          { label: "Inadequado", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_mother_treatment_start",
        label: "Data do Início do Tratamento da mãe",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_partner_treated",
        label: "Parceiro(s) tratado(s) concomitantemente à gestante",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: yesNoUnknownOptions,
      },
    ],
  },
  {
    id: "child_epidemiological_history",
    title: "Antecedentes Epidemiológicos da Criança",
    description: "Informações geográficas e institucionais sobre o local de nascimento ou ocorrência do aborto/natimorto.",
    columns: 3,
    fields: [
      {
        name: "birth_uf",
        label: "UF de nascimento / aborto / natimorto",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "birth_city",
        label: "Município de nascimento / aborto / natimorto",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "birth_city_ibge_code",
        label: "Código (IBGE) do Município de nascimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "birth_place_name",
        label: "Local de Nascimento (Maternidade/Hospital)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "birth_place_code",
        label: "Código do Local de Nascimento",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "child_lab_investigation",
    title: "Dados Laboratoriais da Criança",
    description: "Resultados de testes não treponêmicos, treponêmicos, exames de líquor e evidências microbiológicas.",
    columns: 3,
    fields: [
      {
        name: "st_child_peripheral_blood_test",
        label: "Teste não treponêmico - Sangue Periférico",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_child_peripheral_blood_title",
        label: "Título do teste no sangue periférico",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_child_peripheral_blood",
        label: "Data do teste no sangue periférico",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_child_treponemal_test",
        label: "Teste treponêmico (após dezoito meses)",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Não se aplica", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_child_treponemal",
        label: "Data do teste treponêmico",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_child_liquor_test",
        label: "Teste não treponêmico - Líquor",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Reagente", value: "1" },
          { label: "Não reagente", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "ds_child_liquor_title",
        label: "Título do teste no líquor",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_child_liquor",
        label: "Data do teste no líquor",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_ascending_titration",
        label: "Titulação ascendente",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_treponema_evidence",
        label: "Evidência de Treponema pallidum",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_liquor_alteration",
        label: "Alteração Liquórica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_radiological_alteration",
        label: "Diagnóstico Radiológico da Criança: Alteração do Exame dos Ossos Longos",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Não realizado", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "child_clinical_data",
    title: "Dados Clínicos da Criança",
    description: "Sintomatologia clínica apresentada pelo lactente/recém-nascido.",
    columns: 3,
    fields: [
      {
        name: "tp_clinical_diagnosis",
        label: "Diagnóstico Clínico",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Assintomático", value: "1" },
          { label: "Sintomático", value: "2" },
          { label: "Não se aplica", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      { name: "symptom_jaundice", label: "Presença de sinais e sintomas: Icterícia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_anemia", label: "Presença de sinais e sintomas: Anemia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_splenomegaly", label: "Presença de sinais e sintomas: Esplenomegalia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_rhinitis", label: "Presença de sinais e sintomas: Rinite muco-sanguinolenta", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_hepatomegaly", label: "Presença de sinais e sintomas: Hepatomegalia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_osteochondritis", label: "Presença de sinais e sintomas: Osteocondrite", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_cutaneous_lesions", label: "Presença de sinais e sintomas: Lesões Cutâneas", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_pseudoparalysis", label: "Presença de sinais e sintomas: Pseudoparalisia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_other", label: "Presença de sinais e sintomas: Outro", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
    ],
  },
  {
    id: "case_conclusion",
    title: "Tratamento e Evolução",
    description: "Conduta terapêutica instituída para a criança, evolução clínica e encerramento do caso.",
    columns: 3,
    fields: [
      {
        name: "tp_child_treatment_regimen",
        label: "Esquema de tratamento da criança",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Penicilina G cristalina 100.000 a 150.000 UI/Kg/dia - 10 dias", value: "1" },
          { label: "Penicilina G procaína 50.000 UI/Kg/dia - 10 dias", value: "2" },
          { label: "Penicilina G benzatina 50.000 UI/Kg/dia", value: "3" },
          { label: "Outro esquema", value: "4" },
          { label: "Não realizado", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Vivo", value: "1" },
          { label: "Óbito por sífilis congênita", value: "2" },
          { label: "Óbito por outras causas", value: "3" },
          { label: "Aborto", value: "4" },
          { label: "Natimorto", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const congenitalSyphilisNotificationDefinition = defineNotificationType({
  id: 80,
  slug: "sifilis-congenita",
  label: "Sífilis Congênita",
  description: `Definição de caso:Situação 1: Todo recém-nascido, natimorto ou aborto de mulher com sífilisa não tratada ou tratada de forma não adequadab,c.a Ver definição de sífilis em gestante (situações 1, 2 ou 3).bTratamento adequado: tratamento completo para estágio clínico da sífilis com penicilina benzatina, INICIADO até 30 dias antes do parto. Gestantes que não seenquadrem nesses critérios serão consideradas como tratadas de forma não adequada.c Para fins de notificação de caso de sífilis congênita, não se considera o tratamento da parceria sexual da mãe.Situação 2d: Toda criança com menos de 13 anos de idade com pelo menos uma das seguintes situações:-Manifestação clínica, liquórica ou radiológica de sífilis congênita E teste não treponêmico reagente;-Títulos de teste não treponêmicos do lactente maiores do que os da mãe, em pelo menos duas diluições de amostras de sangue periférico,coletadas simultaneamente no momento do parto;-Títulos de testes não treponêmicos ascendentes em pelo menos duas diluições no seguimento da criança expostae;-Títulos de testes não treponêmicos ainda reagentes após seis meses de idade, em criança adequadamente tratada no período neonatal;-Testes treponêmicos reagentes após 18 meses de idade, sem diagnóstico prévio de sífilis congênita.d Nessa situação, deve ser sempre afastada a possibilidade de sífilis adquirida .e Seguimento da criança exposta: 1, 3, 6, 12 e 18 meses de idadeSituação 3: Evidência microbiológicaf de infecção pelo Treponema pallidum em amostra de secreção nasal ou lesão cutânea, biópsia ou necrópsiade criança, aborto ou natimorto.f Detecção do Treponema pallidum por meio de exames diretos por microscopia (de campo escuro ou com material corado).`,
  sections,
})
