import { z } from "zod";

import {
  defineNotificationType,
  educationLevelOptions,
  raceColorOptions,
  sexOptions,
  yesNoUnknownOptions,
  type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();
const optionalNumberSchema = z.number().optional();
const optionalBooleanSchema = z.boolean().optional();

const serologyOptions = [
  { label: "Reagente", value: "1" },
  { label: "Não Reagente", value: "2" },
  { label: "Inconclusivo", value: "3" },
  { label: "Não Realizado", value: "4" },
];

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e identificação do paciente.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "SÍNDROME DA RUBÉOLA CONGÊNITA",
      },
      {
        name: "co_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string(),
        defaultValue: "P35.0",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF de Notificação",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE) do Município de Notificação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código (Unidade de Saúde)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_diagnosis",
        label: "Data do Diagnóstico",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(3, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit",
        label: "Unidade da Idade",
        kind: "select",
        schema: z.string().default("4"),
        defaultValue: "4",
        options: [
          { label: "Hora", value: "1" },
          { label: "Dia", value: "2" },
          { label: "Mês", value: "3" },
          { label: "Ano", value: "4" },
        ],
      },
      {
        name: "sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: sexOptions,
      },
      {
        name: "gestant",
        label: "Gestante",
        kind: "select",
        schema: z.string(),
        defaultValue: "6",
        options: [
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: raceColorOptions,
      },
      {
        name: "education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "10",
        options: educationLevelOptions,
      },
      {
        name: "sus_card_number",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_location",
    title: "Dados de Residência",
    description: "Localização geográfica do domicílio do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string(),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE) do Município de Residência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "residence_country",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "child_complements",
    title: "Dados Clínicos da Criança",
    description: "Mapeamento dos dados complementares, sinais maiores e menores da infecção congênita.",
    columns: 3,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_newborn_status",
        label: "Recém Nascido",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "A Termo", value: "1" },
          { label: "Prematuro (menos de trinta e sete semanas)", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "nu_birth_weight",
        label: "Peso ao Nascer (gramas)",
        kind: "number",
        schema: optionalNumberSchema,
        defaultValue: 0,
      },
      {
        name: "st_major_signs",
        label: "Sinais Maiores - Grupo I",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_minor_signs",
        label: "Sinais Menores - Grupo II",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      { name: "symptom_cataract", label: "Catarata", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_pigmentary_retinopathy", label: "Retinopatia Pigmentar", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_congenital_glaucoma", label: "Glaucoma Congênito", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_hearing_loss", label: "Deficiência Auditiva", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_congenital_heart_disease", label: "Cardiopatia Congênita", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_psychomotor_retardation", label: "Retardo Psico-Motor", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_microcephaly", label: "Microcefalia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_meningoencephalitis", label: "Meningoencefalite", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_hepatosplenomegaly", label: "Hepatoesplenomegaly", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_jaundice", label: "Icterícia", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_purpura", label: "Púrpura", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
      { name: "symptom_bone_alterations", label: "Alterações Ósseas", kind: "select", schema: z.string(), defaultValue: "9", options: yesNoUnknownOptions },
    ],
  },
  {
    id: "child_laboratorial",
    title: "Dados do Exame Laboratorial da Criança",
    description: "Resultados de investigações sorológicas consecutivas e detecção viral do paciente.",
    columns: 3,
    fields: [
      {
        name: "dt_collection_s1",
        label: "Data da Coleta da Primeira Amostra",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_collection_s2",
        label: "Data da Coleta da Segunda Amostra",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_collection_s3",
        label: "Data da Coleta da Terceira Amostra",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      { name: "serology_measles_igm_s1", label: "Sorologia IgM: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igg_s1", label: "Sorologia IgG: S1", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igm_s2", label: "Sorologia IgM: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igg_s2", label: "Sorologia IgG: S2", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igm_s3", label: "Sorologia IgM: S3", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      { name: "serology_measles_igg_s3", label: "Sorologia IgG: S3", kind: "select", schema: optionalTextSchema, defaultValue: "", options: serologyOptions },
      {
        name: "st_viral_detection_collected",
        label: "Amostra Clínica coletada para Detecção Viral",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      { name: "sample_total_blood", label: "Amostra Clínica: Sangue Total", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      { name: "sample_nasopharyngeal_secretion", label: "Amostra Clínica: Secreção Nasofaringea", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      { name: "sample_urine", label: "Amostra Clínica: Urina", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      { name: "sample_liquor", label: "Amostra Clínica: Líquor", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      {
        name: "tp_viral_detection_result",
        label: "Resultado da Detecção Viral",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Vírus Rubéola Selvagem", value: "1" },
          { label: "Vírus Rubéola Vacinal", value: "2" },
          { label: "Outros vírus", value: "3" },
          { label: "Não detectado", value: "4" },
        ],
      },
    ],
  },
  {
    id: "mother_and_control",
    title: "Dados Complementares da Mãe e Medidas de Controle",
    description: "Mapeamento vacinal materno, história clínica na gestação e condutas de vigilância.",
    columns: 3,
    fields: [
      {
        name: "st_vaccinal_block",
        label: "Bloqueio Vacinal de Contatos",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "st_newborn_isolation",
        label: "Isolamento do Recém-Nascido na Maternidade",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "mother_age",
        label: "Idade da Mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_mother_vaccinated",
        label: "Vacinação da mãe",
        kind: "select",
        schema: z.string(),
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      { name: "vaccine_triple_viral", label: "Vacina: Tríplice Viral (sarampo, caxumba e rubéola)", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      { name: "vaccine_double_viral", label: "Vacina: Dupla Viral (sarampo, rubéola)", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      { name: "vaccine_rubella_monovalent", label: "Vacina: Rubéola (monovalente)", kind: "checkbox", schema: optionalBooleanSchema, defaultValue: false },
      {
        name: "dt_mother_last_vaccine_dose",
        label: "Data da Última Dose da Vacina da mãe",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_mother_symptoms",
        label: "Sinais e Sintomas da mãe",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Apresentou Sintomas de Rubéola", value: "1" },
          { label: "Não Apresentou Sintomas de Rubéola", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_gestation_exposure_period",
        label: "Período da Gestação em que foi Acometida/Exposta",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_mother_confirmation_criterion",
        label: "Critério de Confirmação de Diagnóstico da mãe",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Laboratório", value: "1" },
          { label: "Vínculo-Epidemiológico", value: "2" },
          { label: "Clínico", value: "3" },
        ],
      },
    ],
  },
  {
    id: "case_conclusion",
    title: "Conclusão e Encerramento",
    description: "Classificação final do quadro da criança, diagnóstico diferencial e evolução do agravo.",
    columns: 3,
    fields: [
      {
        name: "nu_medical_record",
        label: "Número do prontuário da criança",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_final_classification",
        label: "Classificação Final",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Confirmado", value: "1" },
          { label: "Infecção Congênita", value: "2" },
          { label: "Descartado", value: "3" },
        ],
      },
      {
        name: "tp_confirmation_criterion",
        label: "Critério de Confirmação/Descarte",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Laboratorial", value: "1" },
          { label: "Clínico", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_discarded_diagnosis",
        label: "Diagnóstico de Descarte",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Toxoplasmose", value: "1" },
          { label: "Citomegalovírus", value: "2" },
          { label: "Sífilis Congênita", value: "3" },
          { label: "Outras", value: "4" },
        ],
      },
      {
        name: "tp_case_evolution",
        label: "Evolução Alta",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Vivo", value: "1" },
          { label: "Óbito por SRC", value: "2" },
          { label: "Óbito por outras causas", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closing",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
] as const satisfies readonly NotificationSectionDefinition[]

export const congenitalRubellaNotificationDefinition = defineNotificationType({
  id: 100,
  slug: "rubeola-congenita",
  label: "Síndrome da Rubéola Congênita",
  description: `CASO SUSPEITO: Todo recém-nascido cuja mãe foi caso suspeito, confirmado de rubéola ou contato de caso confirmado derubéola, durante a gestação ou;Toda criança até 12 meses de idade que apresente sinais clínicos e compatíveis com infecção congênita pelo vírus da rubéola,independente da história materna.`,
  sections,
})
